// TypeSpec → Rust emitter for the OpenBox SDK monorepo.
//
// Mirrors codegen/emitters/typespec-emitter-typescript/ shape. Every
// type, enum, and constant in the Rust crate's package modules is
// produced here from the TypeSpec source of truth at
// `specs/typespec/`. Hand-written Rust code is limited to:
//
//   - `rust/Cargo.toml`      package metadata and platform-glue deps.
//   - `rust/src/lib.rs`      top-level `pub mod` declarations.
//   - `rust/src/<pkg>/mod.rs` one line: `pub use generated::*;`.
//
// Everything else (including each `<pkg>/generated/mod.rs`) is owned
// by this emitter. A `git status` after `npm run specs:compile`
// surfaces drift; the snapshot test in tests/unit/emitter-rust.test.ts
// pins byte-stability for unchanged inputs.

import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve as resolvePathFs } from 'path';
import type {
  EmitContext,
  Enum,
  Model,
  ModelProperty,
  Namespace,
  Operation,
  Program,
  Scalar,
  Type,
  Union,
} from '@typespec/compiler';
import { getDoc } from '@typespec/compiler';
import { listHttpOperationsIn } from '@typespec/http';
import {
  getActivityLabels,
  getActivityRouting,
  getMapsTo,
  getPreset,
} from 'typespec-workflow/decorators';

const BANNER = `// AUTO-GENERATED by codegen/emitters/typespec-emitter-rust. DO NOT EDIT.
// Re-emit with \`npm run specs:compile\` from the repo root.
`;

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const repoRoot = resolveRepoRoot(context);

  emitEnvPackage(program, repoRoot);
  emitTypesPackage(program, repoRoot);
  emitClientPackage(program, repoRoot);
  emitCorePackage(program, repoRoot);
  emitGovernPackage(program, repoRoot);
}

// ---------------------------------------------------------------------------
// Repo root and namespace helpers
// ---------------------------------------------------------------------------

function resolveRepoRoot(context: EmitContext): string {
  const main = context.program.projectRoot ?? process.cwd();
  let dir = main;
  for (let i = 0; i < 10; i++) {
    try {
      const pkg = JSON.parse(readFileSync(resolvePathFs(dir, 'package.json'), 'utf-8'));
      if (pkg.name === 'openbox-sdk') return dir;
    } catch {}
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(`could not locate openbox-sdk repo root from ${main}`);
}

function findNamespace(program: Program, name: string): Namespace | undefined {
  return program.getGlobalNamespaceType().namespaces.get(name);
}

// Models / enums in interface declarations the runtime owns directly.
// Skipping them here means the emitter does not duplicate the contract
// the hand-written reqwest layer implements.
const INTERFACE_NAMES = new Set(['EnvLoader', 'TokenCodec', 'ClientNameResolver', 'OsPathResolver']);

// ---------------------------------------------------------------------------
// env package
// ---------------------------------------------------------------------------

function emitEnvPackage(program: Program, repoRoot: string): void {
  const ns = findNamespace(program, 'OpenboxEnv');
  if (!ns) throw new Error('OpenboxEnv namespace not found');

  const file: string[] = [BANNER, '// Source: specs/typespec/env/main.tsp.', ''];
  file.push('use serde::{Deserialize, Serialize};', '');

  const ctx: EmitNsContext = { program, file, emittedModels: collectEmittedModels(ns) };
  emitNamespaceTypes(ctx, ns);
  emitEnvironmentsConst(ctx, ns, repoRoot);

  writeGeneratedFile(repoRoot, 'rust/src/env/generated', 'env_bindings.rs', file);
  writeGeneratedModRs(repoRoot, 'rust/src/env/generated', ['env_bindings']);
  writeGeneratedReadme(repoRoot, 'rust/src/env/generated', [
    { source: 'specs/typespec/env/main.tsp', reproduces: 'env_bindings.rs: every enum and model declared in the OpenboxEnv namespace, plus the ENVIRONMENTS URL registry from specs/environments.json' },
  ]);
}

// ---------------------------------------------------------------------------
// types package: backend + core wire DTOs
// ---------------------------------------------------------------------------

function emitTypesPackage(program: Program, repoRoot: string): void {
  emitNamespaceFile(program, repoRoot, 'OpenboxBackend', 'rust/src/types/generated', 'backend.rs', 'specs/typespec/backend/main.tsp');
  emitNamespaceFile(program, repoRoot, 'OpenboxCore', 'rust/src/types/generated', 'core.rs', 'specs/typespec/core/main.tsp');
  writeGeneratedModRs(repoRoot, 'rust/src/types/generated', ['backend', 'core']);
  writeGeneratedReadme(repoRoot, 'rust/src/types/generated', [
    { source: 'specs/typespec/backend/main.tsp', reproduces: 'backend.rs: every model, enum, and union declared in the OpenboxBackend namespace' },
    { source: 'specs/typespec/core/main.tsp', reproduces: 'core.rs: every model, enum, and union declared in the OpenboxCore namespace' },
  ]);
}

// ---------------------------------------------------------------------------
// client package: backend wrapper scaffolding (manifest only for now)
// ---------------------------------------------------------------------------

function emitClientPackage(program: Program, repoRoot: string): void {
  const manifest: string[] = [BANNER, '// Source: specs/typespec/backend/main.tsp.', ''];
  manifest.push('// Endpoint manifest. Hand-written tooling iterates this list when');
  manifest.push('// it needs to enumerate the backend HTTP surface (CLI generation,');
  manifest.push('// drift checks). Method wrappers live alongside in wrapper_methods.rs.');
  manifest.push('');
  appendEndpointManifest(program, manifest, 'OpenboxBackend', 'BACKEND_ENDPOINT_MANIFEST');
  writeGeneratedFile(repoRoot, 'rust/src/client/generated', 'endpoint_manifest.rs', manifest);

  emitWrapperMethods(program, repoRoot, {
    namespaceName: 'OpenboxBackend',
    outDir: 'rust/src/client/generated',
    fileName: 'wrapper_methods.rs',
    source: 'specs/typespec/backend/main.tsp',
    clientStruct: 'OpenBoxClient',
    clientModule: 'crate::client',
  });

  writeGeneratedModRs(repoRoot, 'rust/src/client/generated', [
    'endpoint_manifest',
    'wrapper_methods',
  ]);
  writeGeneratedReadme(repoRoot, 'rust/src/client/generated', [
    { source: 'specs/typespec/backend/main.tsp', reproduces: 'endpoint_manifest.rs: the BACKEND_ENDPOINT_MANIFEST array enumerating every backend HTTP operation' },
    { source: 'specs/typespec/backend/main.tsp', reproduces: 'wrapper_methods.rs: one async fn on OpenBoxClient per backend HTTP operation' },
  ]);
}

function emitCorePackage(program: Program, repoRoot: string): void {
  const manifest: string[] = [BANNER, '// Source: specs/typespec/core/main.tsp.', ''];
  manifest.push('// Endpoint manifest. Hand-written tooling iterates this list when');
  manifest.push('// it needs to enumerate the core governance HTTP surface. Method');
  manifest.push('// wrappers live alongside in wrapper_methods.rs.');
  manifest.push('');
  appendEndpointManifest(program, manifest, 'OpenboxCore', 'CORE_ENDPOINT_MANIFEST');
  writeGeneratedFile(repoRoot, 'rust/src/core/generated', 'endpoint_manifest.rs', manifest);

  emitWrapperMethods(program, repoRoot, {
    namespaceName: 'OpenboxCore',
    outDir: 'rust/src/core/generated',
    fileName: 'wrapper_methods.rs',
    source: 'specs/typespec/core/main.tsp',
    clientStruct: 'OpenBoxCoreClient',
    clientModule: 'crate::core',
  });

  writeGeneratedModRs(repoRoot, 'rust/src/core/generated', [
    'endpoint_manifest',
    'wrapper_methods',
    'govern',
  ]);
  writeGeneratedReadme(repoRoot, 'rust/src/core/generated', [
    { source: 'specs/typespec/core/main.tsp', reproduces: 'endpoint_manifest.rs: the CORE_ENDPOINT_MANIFEST array enumerating every core governance HTTP operation' },
    { source: 'specs/typespec/core/main.tsp', reproduces: 'wrapper_methods.rs: one async fn on OpenBoxCoreClient per core HTTP operation' },
    { source: 'specs/typespec/govern/main.tsp', reproduces: 'govern.rs: the canonical event_type / activity_type / verdict_arm sets and the spec-driven activity_type → display label table' },
  ]);
}

// ---------------------------------------------------------------------------
// govern package: canonical sets + spec-driven activity-label table
// ---------------------------------------------------------------------------
//
// Mirror of `emitGovernProtocol` in the TS emitter, narrowed to the
// pieces Rust consumers need today: the four canonical sets the TS side
// also exports plus the activity_type → display label table. The full
// protocol model graph (Workflow*, Verdict*, ActivityStage, etc.) is
// already reachable through `OpenboxCore` types; we don't re-emit it.
//
// Output lands at `rust/src/core/generated/govern.rs` to mirror the TS
// path `ts/src/core-client/generated/govern.ts`. The activity-label
// table is sorted by activity_type so callers can binary-search it.

function emitGovernPackage(program: Program, repoRoot: string): void {
  const ns = findNamespace(program, 'OpenboxGovern');
  const file: string[] = [BANNER, '// Source: specs/typespec/govern/main.tsp.', ''];

  if (!ns) {
    // Stub when the namespace is absent so the mod.rs reference
    // registered in `emitCorePackage` still compiles.
    file.push('// OpenboxGovern namespace not found in this spec compile.');
    file.push('');
    writeGeneratedFile(repoRoot, 'rust/src/core/generated', 'govern.rs', file);
    return;
  }

  // Canonical event-type strings live as the `CanonicalEventType` enum
  // on the namespace; pick the wire `value` string when present so we
  // never emit the TypeSpec member identifier by accident.
  const eventTypes: string[] = [];
  for (const [enumName, enumType] of ns.enums) {
    if (enumName !== 'CanonicalEventType') continue;
    for (const m of enumType.members.values()) {
      eventTypes.push(String(m.value ?? m.name));
    }
  }

  const verdictArms: string[] = [];
  for (const [enumName, enumType] of ns.enums) {
    if (enumName !== 'VerdictArm') continue;
    for (const m of enumType.members.values()) {
      verdictArms.push(String(m.value ?? m.name));
    }
  }

  // Activity-type vocabulary: union of every `@maps_to` activity_type
  // declared on a `@preset` interface plus every value in an
  // `@activityRouting` adapter table. Mirrors the TS emitter's walk so
  // the canonical set stays identical across language SDKs.
  const activityTypes = new Set<string>();
  for (const [, iface] of ns.interfaces) {
    if (!getPreset(program, iface)) continue;
    for (const [opName, op] of iface.operations) {
      const m = getMapsTo(program, op);
      if (m && m.activityType) {
        activityTypes.add(m.activityType);
      } else if (m) {
        activityTypes.add(opName);
      }
    }
  }
  const adaptersNs = findNamespace(program, 'OpenboxGovern.Adapters');
  if (adaptersNs) {
    for (const [, iface] of adaptersNs.interfaces) {
      for (const [, op] of iface.operations) {
        const ar = getActivityRouting(program, op);
        if (!ar) continue;
        for (const v of Object.values(ar.table)) activityTypes.add(v);
      }
    }
  }

  // `@activityLabels` decorator backs the curated display labels. Drop
  // entries that aren't in the canonical set so the emitted table never
  // drifts past the spec-recognized vocabulary; consumers fall back to
  // the title-case formatter in `openbox_sdk::approvals::format` for
  // anything not in this table.
  const labelsBinding = getActivityLabels(program, ns);
  const labelTable: Record<string, string> = {};
  if (labelsBinding) {
    for (const [k, v] of Object.entries(labelsBinding.table)) {
      if (activityTypes.has(k)) labelTable[k] = v;
    }
  }

  const sortedEventTypes = [...eventTypes].sort();
  const sortedActivityTypes = [...activityTypes].sort();
  const sortedVerdictArms = [...verdictArms].sort();
  const sortedLabelKeys = Object.keys(labelTable).sort();

  file.push('/// The canonical `event_type` strings the core service recognizes.');
  file.push('/// Anything else on the wire is a protocol bug.');
  file.push("pub const CANONICAL_EVENT_TYPES: &[&str] = &[");
  for (const t of sortedEventTypes) file.push(`    ${JSON.stringify(t)},`);
  file.push('];');
  file.push('');

  file.push('/// First-party `activity_type` vocabulary: every activity_type declared on a');
  file.push('/// `@preset` method or in an `@activityRouting` adapter table. Custom-preset');
  file.push('/// domain agents legitimately emit activity_types outside this set; treat it');
  file.push('/// as an allowlist for protocol-conformance reports, not for runtime gating.');
  file.push("pub const CANONICAL_ACTIVITY_TYPES: &[&str] = &[");
  for (const t of sortedActivityTypes) file.push(`    ${JSON.stringify(t)},`);
  file.push('];');
  file.push('');

  file.push('/// Spec-driven display labels for canonical activity_types. Sorted by');
  file.push('/// activity_type so `canonical_activity_label` can binary-search. Source of');
  file.push('/// truth for any UI that renders activity types (mobile, VS Code extension,');
  file.push('/// macOS approver, CLI list views). Consumers fall back to a title-case');
  file.push('/// formatter for activity_types not in this table; custom-preset domain');
  file.push("/// agents emit free-form strings that legitimately aren't covered here.");
  file.push("pub const CANONICAL_ACTIVITY_LABELS: &[(&str, &str)] = &[");
  for (const k of sortedLabelKeys) {
    file.push(`    (${JSON.stringify(k)}, ${JSON.stringify(labelTable[k])}),`);
  }
  file.push('];');
  file.push('');

  file.push('/// Look up the spec-driven display label for an `activity_type` string.');
  file.push('/// Returns `None` for non-canonical values; callers should fall back to a');
  file.push('/// title-case formatter (see `openbox_sdk::approvals::format::format_label`).');
  file.push('pub fn canonical_activity_label(activity_type: &str) -> Option<&\'static str> {');
  file.push('    CANONICAL_ACTIVITY_LABELS');
  file.push('        .binary_search_by(|(k, _)| (*k).cmp(activity_type))');
  file.push('        .ok()');
  file.push('        .map(|i| CANONICAL_ACTIVITY_LABELS[i].1)');
  file.push('}');
  file.push('');

  file.push('/// Every verdict arm the runtime emits. Production sets typically exclude');
  file.push('/// `constrain`; consumers can re-filter.');
  file.push("pub const CANONICAL_VERDICT_ARMS: &[&str] = &[");
  for (const a of sortedVerdictArms) file.push(`    ${JSON.stringify(a)},`);
  file.push('];');
  file.push('');

  writeGeneratedFile(repoRoot, 'rust/src/core/generated', 'govern.rs', file);
}

// ---------------------------------------------------------------------------
// Namespace → Rust file
// ---------------------------------------------------------------------------

interface EmitNsContext {
  program: Program;
  file: string[];
  /** Set of model names this namespace will emit. Used to decide
   *  whether a field-type reference resolves to an in-file struct or
   *  needs to fall back to `serde_json::Value`. Generic templates and
   *  their unnamed instantiations live outside this set. */
  emittedModels: Set<string>;
}

function emitNamespaceFile(
  program: Program,
  repoRoot: string,
  namespaceName: string,
  outDir: string,
  fileName: string,
  source: string,
): void {
  const ns = findNamespace(program, namespaceName);
  if (!ns) {
    // Empty file when the namespace is absent; mod.rs still wires it.
    const file = [BANNER, `// Source: ${source} (namespace ${namespaceName} not found).`, ''];
    writeGeneratedFile(repoRoot, outDir, fileName, file);
    return;
  }
  const file: string[] = [BANNER, `// Source: ${source}.`, ''];
  file.push('use serde::{Deserialize, Serialize};', '');
  const ctx: EmitNsContext = { program, file, emittedModels: collectEmittedModels(ns) };
  emitNamespaceTypes(ctx, ns);
  writeGeneratedFile(repoRoot, outDir, fileName, file);
}

function collectEmittedModels(ns: Namespace): Set<string> {
  const out = new Set<string>();
  for (const [name, m] of ns.models) {
    if (INTERFACE_NAMES.has(name)) continue;
    if (m.name === '') continue;
    if (isInstantiatedTemplate(m)) continue;
    out.add(m.name);
  }
  for (const [, e] of ns.enums) out.add(e.name);
  for (const [, u] of ns.unions) {
    if (u.name) out.add(u.name);
  }
  return out;
}

function emitNamespaceTypes(ctx: EmitNsContext, ns: Namespace): void {
  for (const [, e] of ns.enums) {
    appendEnum(ctx, e);
    ctx.file.push('');
  }
  for (const [, u] of ns.unions) {
    appendUnion(ctx, u);
    ctx.file.push('');
  }
  // Emit each declared model ONCE. Generic templates surface via their
  // uninstantiated form (`PaginatedResponse<T>`); we emit the generic
  // and skip every concrete instantiation that shares the same name.
  const seenNames = new Set<string>();
  for (const [name, m] of ns.models) {
    if (INTERFACE_NAMES.has(name)) continue;
    if (m.name === '') continue;
    // Drop concrete instantiations that resolve to the same name as
    // their template; the generic-emitted form covers them via type
    // arguments at the call site.
    if (isInstantiatedTemplate(m)) continue;
    if (seenNames.has(m.name)) continue;
    seenNames.add(m.name);
    appendModel(ctx, m);
    ctx.file.push('');
  }
}

function isInstantiatedTemplate(m: Model): boolean {
  return (m as { templateMapper?: unknown }).templateMapper !== undefined;
}

function isTemplateModel(m: Model): boolean {
  const node = (m as { node?: { templateParameters?: { length: number } } }).node;
  return (node?.templateParameters?.length ?? 0) > 0;
}

function templateArgs(m: Model): Type[] {
  const mapper = (m as { templateMapper?: { args?: Type[] } }).templateMapper;
  return mapper?.args ?? [];
}

function appendEnum(ctx: EmitNsContext, e: Enum): void {
  ctx.file.push(...renderDoc(getDoc(ctx.program, e)));
  ctx.file.push('#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]');
  ctx.file.push('#[serde(rename_all = "lowercase")]');
  ctx.file.push(`pub enum ${e.name} {`);
  for (const member of e.members.values()) {
    const wire = typeof member.value === 'string' ? member.value : member.name;
    if (wire !== member.name.toLowerCase()) {
      ctx.file.push(`    #[serde(rename = "${wire}")]`);
    }
    ctx.file.push(`    ${pascal(member.name)},`);
  }
  ctx.file.push('}');
}

function appendUnion(ctx: EmitNsContext, u: Union): void {
  ctx.file.push(...renderDoc(getDoc(ctx.program, u)));
  // Untagged unions of literals: emit as enum of unit variants.
  // Union of arbitrary types: bail to serde_json::Value alias.
  const variants = [...u.variants.values()];
  const allLiterals = variants.every((v) => v.type.kind === 'String');
  if (allLiterals) {
    ctx.file.push('#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]');
    ctx.file.push('#[serde(rename_all = "lowercase")]');
    ctx.file.push(`pub enum ${u.name ?? 'Anonymous'} {`);
    for (const v of variants) {
      const lit = (v.type as { value: string }).value;
      ctx.file.push(`    #[serde(rename = "${lit}")]`);
      ctx.file.push(`    ${pascal(String(v.name) || lit)},`);
    }
    ctx.file.push('}');
    return;
  }
  ctx.file.push(`pub type ${u.name ?? 'Anonymous'} = serde_json::Value;`);
}

function appendModel(ctx: EmitNsContext, m: Model): void {
  ctx.file.push(...renderDoc(getDoc(ctx.program, m)));
  ctx.file.push('#[derive(Debug, Clone, Serialize, Deserialize)]');
  const params = templateParamNames(m);
  if (params.length > 0) {
    // Let serde's derive infer per-field bounds (`T: Serialize`,
    // `T: Deserialize<'de>`) instead of declaring a where clause
    // ourselves. Mixing both produces E0283: the inferred lifetime
    // bound and a `DeserializeOwned` where clause look like two
    // distinct impls to the resolver.
    ctx.file.push(`pub struct ${m.name}<${params.join(', ')}> {`);
  } else {
    ctx.file.push(`pub struct ${m.name} {`);
  }
  for (const [propName, prop] of m.properties) {
    appendProperty(ctx, propName, prop, m);
  }
  ctx.file.push('}');
}

function templateParamNames(m: Model): string[] {
  // TypeSpec's template AST node varies in shape between compiler
  // versions and the surface API does not expose a typed accessor.
  // The `node` carries either:
  //   - `node.templateParameters: TemplateParameterDeclarationNode[]`
  //   - `node.templateParameters: { parameters: ...[] }` (older shape)
  // Try both. Returns [] for instantiated forms.
  if ((m as { templateMapper?: unknown }).templateMapper) return [];
  const node = (m as {
    node?: {
      templateParameters?:
        | { parameters?: { id: { sv: string } }[] }
        | { id: { sv: string } }[];
    };
  }).node;
  const tp = node?.templateParameters;
  if (!tp) return [];
  if (Array.isArray(tp)) {
    return tp.map((p) => p.id.sv);
  }
  return (tp.parameters ?? []).map((p) => p.id.sv);
}

function appendProperty(
  ctx: EmitNsContext,
  propName: string,
  prop: ModelProperty,
  parent: Model,
): void {
  for (const line of renderDoc(getDoc(ctx.program, prop))) ctx.file.push(`    ${line}`);
  const rustName = snake(propName);
  const ty = renderType(ctx, prop.type, prop.optional, parent);
  if (rustName !== propName) {
    ctx.file.push(`    #[serde(rename = "${propName}")]`);
  }
  if (prop.optional) {
    ctx.file.push('    #[serde(default, skip_serializing_if = "Option::is_none")]');
  }
  ctx.file.push(`    pub ${escapeRustKeyword(rustName)}: ${ty},`);
}

function renderType(ctx: EmitNsContext, t: Type, optional: boolean, parent?: Model): string {
  const inner = renderTypeInner(ctx, t, parent);
  // Self-reference (e.g. `cause: ErrorInfo` on `model ErrorInfo`) is
  // infinite-size in Rust unless boxed. Detect and wrap before
  // applying `Option<>` so it stays `Option<Box<Self>>`.
  if (parent && t.kind === 'Model' && (t as Model).name === parent.name) {
    return optional ? `Option<Box<${inner}>>` : `Box<${inner}>`;
  }
  return optional ? `Option<${inner}>` : inner;
}

function renderTypeInner(ctx: EmitNsContext, t: Type, parent?: Model): string {
  switch (t.kind) {
    case 'Scalar':
      return renderScalar(t as Scalar);
    case 'Model': {
      const m = t as Model;
      // `T[]` inside a template body is the `Array` model with
      // `templateMapper.args = [T]` but no resolved `indexer` yet.
      // Cover both the resolved and unresolved cases.
      if (m.name === 'Array') {
        if (m.indexer) {
          return `Vec<${renderTypeInner(ctx, m.indexer.value, parent)}>`;
        }
        const arg = templateArgs(m)[0];
        if (arg) return `Vec<${renderTypeInner(ctx, arg, parent)}>`;
      }
      if (m.name === 'Record') {
        if (m.indexer) {
          return `std::collections::HashMap<String, ${renderTypeInner(ctx, m.indexer.value, parent)}>`;
        }
        const arg = templateArgs(m)[0];
        if (arg) return `std::collections::HashMap<String, ${renderTypeInner(ctx, arg, parent)}>`;
      }
      if (parent && m.name === parent.name) return m.name;
      // Instantiated template: render with concrete type arguments,
      // e.g. `PaginatedResponse<Agent>`.
      if (isInstantiatedTemplate(m)) {
        const args = templateArgs(m).map((a) => renderTypeInner(ctx, a));
        if (m.name && ctx.emittedModels.has(m.name)) {
          return args.length > 0 ? `${m.name}<${args.join(', ')}>` : m.name;
        }
        return 'serde_json::Value';
      }
      if (m.name && ctx.emittedModels.has(m.name)) return m.name;
      return 'serde_json::Value';
    }
    case 'Enum':
      return (t as Enum).name;
    case 'TemplateParameter':
      return (t as { node: { id: { sv: string } } }).node.id.sv;
    case 'Union': {
      const u = t as Union;
      if (u.name && ctx.emittedModels.has(u.name)) return u.name;
      const variants = [...u.variants.values()];
      if (variants.every((v) => v.type.kind === 'String')) {
        // Fallback: untagged literal union the emitter did not name.
        // Carry as a String; downstream callers compare against
        // literals.
        return 'String';
      }
      return 'serde_json::Value';
    }
    case 'Intrinsic':
      return 'serde_json::Value';
    default:
      // Unknown kind. Surface in stderr during emit so we can iterate
      // on coverage; runtime safety stays via serde_json::Value.
      // eslint-disable-next-line no-console
      console.error(`[typespec-emitter-rust] unhandled type kind: ${t.kind}`);
      return 'serde_json::Value';
  }
}

function renderScalar(s: Scalar): string {
  switch (s.name) {
    case 'string':
      return 'String';
    case 'boolean':
      return 'bool';
    case 'int8':
      return 'i8';
    case 'int16':
      return 'i16';
    case 'int32':
      return 'i32';
    case 'int64':
    case 'safeint':
    case 'integer':
      return 'i64';
    case 'uint8':
      return 'u8';
    case 'uint16':
      return 'u16';
    case 'uint32':
      return 'u32';
    case 'uint64':
      return 'u64';
    case 'float':
    case 'float32':
      return 'f32';
    case 'float64':
    case 'numeric':
      return 'f64';
    case 'decimal':
    case 'decimal128':
      return 'String';
    case 'bytes':
      return 'Vec<u8>';
    case 'url':
      return 'String';
    case 'utcDateTime':
    case 'offsetDateTime':
    case 'plainDate':
    case 'plainTime':
    case 'duration':
      return 'String';
    default:
      // Custom scalar: surface as its own type so a separate `pub type`
      // alias can be hand-written if needed.
      return s.name ? pascal(s.name) : 'String';
  }
}

// ---------------------------------------------------------------------------
// ENVIRONMENTS const
// ---------------------------------------------------------------------------

function emitEnvironmentsConst(ctx: EmitNsContext, ns: Namespace, repoRoot: string): void {
  const envName = ns.enums.get('EnvName');
  if (!envName) return;

  const envFile = resolvePathFs(repoRoot, 'specs/environments.json');
  const envs = JSON.parse(readFileSync(envFile, 'utf-8')) as Record<
    string,
    { apiUrl: string; coreUrl: string; platformUrl: string }
  >;

  ctx.file.push('/// Static-string twin of `EnvConfig`. The runtime owns `EnvConfig` with');
  ctx.file.push('/// `String` fields for runtime URL overrides; this carries borrows into');
  ctx.file.push("/// the embedded `ENVIRONMENTS` table.");
  ctx.file.push('#[derive(Debug, Clone, Copy)]');
  ctx.file.push('pub struct EnvConfigStatic {');
  ctx.file.push("    pub api_url: &'static str,");
  ctx.file.push("    pub core_url: &'static str,");
  ctx.file.push("    pub platform_url: &'static str,");
  ctx.file.push('}');
  ctx.file.push('');
  ctx.file.push('/// Canonical URL registry mirrored from `specs/environments.json`.');
  ctx.file.push('pub const ENVIRONMENTS: &[(EnvName, EnvConfigStatic)] = &[');
  for (const member of envName.members.values()) {
    const wire = typeof member.value === 'string' ? member.value : member.name;
    const cfg = envs[wire];
    if (!cfg) throw new Error(`specs/environments.json missing entry for "${wire}"`);
    ctx.file.push('    (');
    ctx.file.push(`        EnvName::${pascal(member.name)},`);
    ctx.file.push('        EnvConfigStatic {');
    ctx.file.push(`            api_url: ${JSON.stringify(cfg.apiUrl)},`);
    ctx.file.push(`            core_url: ${JSON.stringify(cfg.coreUrl)},`);
    ctx.file.push(`            platform_url: ${JSON.stringify(cfg.platformUrl)},`);
    ctx.file.push('        },');
    ctx.file.push('    ),');
  }
  ctx.file.push('];');
}

// ---------------------------------------------------------------------------
// Endpoint manifest
// ---------------------------------------------------------------------------

interface ManifestEntry {
  operationId: string;
  path: string;
  verb: string;
}

function appendEndpointManifest(
  program: Program,
  file: string[],
  namespaceName: string,
  constName: string,
): void {
  const ns = findNamespace(program, namespaceName);
  const entries: ManifestEntry[] = [];
  if (ns) {
    walkOperations(ns, (operationId, path, verb) => {
      entries.push({ operationId, path, verb });
    });
  }

  file.push(`/// One entry per HTTP operation declared in the spec. Stable iteration`);
  file.push(`/// order matches declaration order.`);
  file.push('#[derive(Debug, Clone, Copy)]');
  file.push('pub struct EndpointManifestEntry {');
  file.push("    pub operation_id: &'static str,");
  file.push("    pub path: &'static str,");
  file.push("    pub verb: &'static str,");
  file.push('}');
  file.push('');
  file.push(`pub const ${constName}: &[EndpointManifestEntry] = &[`);
  for (const e of entries) {
    file.push('    EndpointManifestEntry {');
    file.push(`        operation_id: ${JSON.stringify(e.operationId)},`);
    file.push(`        path: ${JSON.stringify(e.path)},`);
    file.push(`        verb: ${JSON.stringify(e.verb.toUpperCase())},`);
    file.push('    },');
  }
  file.push('];');
}

function walkOperations(
  ns: Namespace,
  visit: (operationId: string, path: string, verb: string) => void,
): void {
  for (const [, op] of ns.operations) {
    const httpRoute = (op as unknown as { route?: { path: string } }).route;
    if (!httpRoute) continue;
    const verb = (op as unknown as { verb?: string }).verb ?? 'POST';
    visit(op.name, httpRoute.path, verb);
  }
  for (const [, child] of ns.namespaces) {
    walkOperations(child, visit);
  }
}

// ---------------------------------------------------------------------------
// Wrapper-method emit
// ---------------------------------------------------------------------------

interface WrapperEmitOptions {
  namespaceName: string;
  outDir: string;
  fileName: string;
  source: string;
  /** Name of the hand-written struct the impl block extends, e.g.
   *  `OpenBoxClient`. The struct lives in `<clientModule>` and is
   *  expected to expose `request_get` / `request_post` / etc. */
  clientStruct: string;
  clientModule: string;
}

interface WrapperMethodSpec {
  methodName: string;
  verb: 'get' | 'post' | 'put' | 'patch' | 'delete';
  path: string;
  pathParams: { name: string }[];
  bodyType: string | null;
  responseType: string;
  hasQuery: boolean;
  doc: string | undefined;
}

let CURATED_METHOD_NAMES: Record<string, string> | null = null;
function curatedMethodNames(repoRoot: string): Record<string, string> {
  if (CURATED_METHOD_NAMES) return CURATED_METHOD_NAMES;
  try {
    CURATED_METHOD_NAMES = JSON.parse(
      readFileSync(resolvePathFs(repoRoot, 'codegen/method-names.json'), 'utf-8'),
    ) as Record<string, string>;
  } catch {
    CURATED_METHOD_NAMES = {};
  }
  return CURATED_METHOD_NAMES;
}

function emitWrapperMethods(
  program: Program,
  repoRoot: string,
  opts: WrapperEmitOptions,
): void {
  const ns = findNamespace(program, opts.namespaceName);
  if (!ns) return;

  const [ops] = listHttpOperationsIn(program, ns);
  const file: string[] = [BANNER, `// Source: ${opts.source}.`, ''];
  file.push('#![allow(unused_imports, clippy::too_many_arguments)]');
  file.push('use crate::types::*;');
  file.push(`use ${opts.clientModule}::{${opts.clientStruct}, ApiError};`);
  file.push('');

  const ctx: EmitNsContext = {
    program,
    file,
    emittedModels: collectGlobalEmittedModels(program),
  };

  const names = curatedMethodNames(repoRoot);
  const seen = new Set<string>();
  const methods: WrapperMethodSpec[] = [];
  for (const op of ops) {
    const spec = methodSpecFor(ctx, op, names);
    if (!spec) continue;
    if (seen.has(spec.methodName)) continue;
    seen.add(spec.methodName);
    methods.push(spec);
  }

  file.push(`impl ${opts.clientStruct} {`);
  for (const m of methods) {
    appendWrapperMethod(file, m);
    file.push('');
  }
  // Drop the trailing blank line so the file ends with a single \n.
  while (file.length > 0 && file[file.length - 1] === '') file.pop();
  file.push('}');

  writeGeneratedFile(repoRoot, opts.outDir, opts.fileName, file);
}

function collectGlobalEmittedModels(program: Program): Set<string> {
  // Wrapper-method types reference models from any `Openbox*` namespace
  // (backend ops sometimes return env / shared types). Union every
  // top-level OpenBox namespace so renderType resolves names from any
  // of them without a per-namespace re-lookup.
  const out = new Set<string>();
  const root = program.getGlobalNamespaceType();
  for (const [name, ns] of root.namespaces) {
    if (!name.startsWith('Openbox')) continue;
    for (const m of collectEmittedModels(ns)) out.add(m);
  }
  return out;
}

type HttpOp = ReturnType<typeof listHttpOperationsIn>[0][number];

function methodSpecFor(
  ctx: EmitNsContext,
  op: HttpOp,
  curated: Record<string, string>,
): WrapperMethodSpec | null {
  const opId = op.operation.name;
  let methodName = curated[opId];
  if (!methodName) {
    // Fallback: strip the `<Tag>Controller_` prefix. Mirrors the TS
    // emitter heuristic; new ops without a curated entry get the bare
    // verb (e.g. `list`) and may collide. Curating in
    // codegen/method-names.json fixes it.
    methodName = opId;
    const m = opId.match(/^([A-Z][a-zA-Z]*Controller)_(.+)$/);
    if (m) methodName = m[2];
  }

  const verb = op.verb.toLowerCase();
  if (!isHttpVerb(verb)) return null;

  const pathParams: { name: string }[] = [];
  let hasQuery = false;
  for (const p of op.parameters.parameters) {
    if (p.type === 'path') pathParams.push({ name: p.name });
    else if (p.type === 'query') hasQuery = true;
  }

  let bodyType: string | null = null;
  if (op.parameters.body && 'type' in op.parameters.body && op.parameters.body.type) {
    bodyType = renderTypeInner(ctx, op.parameters.body.type);
  }

  // Pick the first 2xx body. `Body<T>` wrappers expose `.type` as the
  // unwrapped inner T already (TypeSpec instantiates the template).
  let responseType = 'serde_json::Value';
  for (const r of op.responses) {
    const status =
      typeof r.statusCodes === 'number'
        ? r.statusCodes
        : typeof r.statusCodes === 'object' && r.statusCodes !== null && 'start' in r.statusCodes
          ? (r.statusCodes as { start: number }).start
          : 0;
    if (status < 200 || status >= 300) continue;
    for (const content of r.responses) {
      if (content.body && 'type' in content.body && content.body.type) {
        responseType = renderTypeInner(ctx, content.body.type);
        break;
      }
    }
    break;
  }

  return {
    methodName,
    verb,
    path: op.path,
    pathParams,
    bodyType,
    responseType,
    hasQuery,
    doc: getDoc(ctx.program, op.operation as unknown as Operation),
  };
}

function isHttpVerb(v: string): v is WrapperMethodSpec['verb'] {
  return v === 'get' || v === 'post' || v === 'put' || v === 'patch' || v === 'delete';
}

function appendWrapperMethod(file: string[], m: WrapperMethodSpec): void {
  for (const line of renderDoc(m.doc)) file.push(`    ${line}`);

  const args: string[] = ['&self'];
  for (const p of m.pathParams) args.push(`${snake(p.name)}: &str`);
  if (m.bodyType) args.push(`body: &${m.bodyType}`);
  if (m.hasQuery) args.push('query: Option<&serde_json::Value>');

  file.push(
    `    pub async fn ${snake(m.methodName)}(${args.join(', ')}) -> Result<${m.responseType}, ApiError> {`,
  );

  // `format!("/agent/{}/approval/{}/decide", agent_id, approval_id)`
  // for any path with `{param}` placeholders, otherwise a static &str.
  let pathExpr: string;
  if (m.pathParams.length === 0) {
    pathExpr = JSON.stringify(m.path);
  } else {
    const fmt = m.path.replace(/\{[^}]+\}/g, '{}');
    const callArgs = m.pathParams.map((p) => snake(p.name)).join(', ');
    pathExpr = `&format!(${JSON.stringify(fmt)}, ${callArgs})`;
  }

  // Every `request_<verb>` helper takes the same shape:
  //   self.request_<verb>(path, body, query).await
  // Body and query slots accept `Option<&T>`. Empty slots emit
  // `None::<&()>` (body) or `None::<&serde_json::Value>` (query); the
  // sentinel types resolve Rust generic inference and impl `Serialize`
  // without allocating. A uniform call shape covers irregular cases
  // like GET-with-body and DELETE-with-body the spec carries.
  const bodyArg = m.bodyType ? 'Some(body)' : 'None::<&()>';
  const queryArg = m.hasQuery ? 'query' : 'None::<&serde_json::Value>';
  file.push(`        self.request_${m.verb}(${pathExpr}, ${bodyArg}, ${queryArg}).await`);
  file.push('    }');
}

// ---------------------------------------------------------------------------
// File writers
// ---------------------------------------------------------------------------

function writeGeneratedFile(repoRoot: string, dirRel: string, name: string, lines: string[]): void {
  const out = resolvePathFs(repoRoot, dirRel, name);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, lines.join('\n').replace(/\n+$/, '\n'));
}

function writeGeneratedModRs(repoRoot: string, dirRel: string, modules: string[]): void {
  const lines = [BANNER, ''];
  for (const m of modules) lines.push(`mod ${m};`);
  lines.push('');
  // Re-export every module's items except `wrapper_methods`. That file
  // contains inherent `impl` blocks (no public types or fns), so a
  // `pub use wrapper_methods::*` is empty and trips the compiler's
  // unused-imports lint.
  for (const m of modules) {
    if (m === 'wrapper_methods') continue;
    lines.push(`pub use ${m}::*;`);
  }
  lines.push('');
  writeGeneratedFile(repoRoot, dirRel, 'mod.rs', lines);
}

interface ReadmeRow {
  source: string;
  reproduces: string;
}

function writeGeneratedReadme(repoRoot: string, dirRel: string, rows: ReadmeRow[]): void {
  const lines: string[] = [];
  lines.push(`# \`${dirRel.replace(/^rust\//, '')}\``);
  lines.push('');
  lines.push('**AUTO-GENERATED. Do not hand-edit.**');
  lines.push('');
  lines.push('| Source | Reproduces |');
  lines.push('|---|---|');
  for (const r of rows) {
    lines.push(`| \`${r.source}\` | ${r.reproduces} |`);
  }
  lines.push('| `codegen/emitters/typespec-emitter-rust/src/index.ts` | the emit logic |');
  lines.push('');
  lines.push('Regenerate with `npm run specs:compile`.');
  lines.push('');
  const out = resolvePathFs(repoRoot, dirRel, 'README.md');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, lines.join('\n'));
}

// ---------------------------------------------------------------------------
// String helpers
// ---------------------------------------------------------------------------

function pascal(s: string): string {
  // Handles snake_case, kebab-case, dotted, and existing PascalCase
  // inputs. Splits on any non-alphanumeric run, capitalizes each
  // chunk, and rejoins. Already-PascalCase strings pass through
  // because the split yields a single chunk.
  const parts = s.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return s;
  return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function snake(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function escapeRustKeyword(name: string): string {
  const reserved = new Set([
    'as', 'async', 'await', 'break', 'const', 'continue', 'crate', 'dyn', 'else',
    'enum', 'extern', 'false', 'fn', 'for', 'if', 'impl', 'in', 'let', 'loop',
    'match', 'mod', 'move', 'mut', 'pub', 'ref', 'return', 'self', 'Self',
    'static', 'struct', 'super', 'trait', 'true', 'type', 'union', 'unsafe',
    'use', 'where', 'while', 'yield',
  ]);
  return reserved.has(name) ? `r#${name}` : name;
}

function renderDoc(text: string | undefined): string[] {
  if (!text) return [];
  return text.split('\n').map((line) => `/// ${line.trimEnd()}`);
}
