import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { Model, Namespace, Program, Type } from '@typespec/compiler';
import { resolvePath } from '@typespec/compiler';
import { listHttpOperationsIn } from '@typespec/http';
import {
  getBackendPermissions,
  getMapsTo,
  getPreset,
  getProviderCapabilities,
  getSdkMethodNames,
  getSdkTargets,
} from 'typespec-workflow/decorators';

const PYTHON_BANNER = `# AUTO-GENERATED by codegen/emitters/ts. DO NOT EDIT.
# Regenerate with: npm run specs:compile
from __future__ import annotations
`;

const PYTHON_KEYWORDS = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield',
]);

interface PythonEndpointEntry {
  operation_id: string;
  method_name: string;
  verb: string;
  path: string;
  path_pattern: string;
}

interface PythonPresetMethod {
  name: string;
  eventType?: string;
  activityType?: string;
}

interface PythonPresetEntry {
  preset: string;
  methods: PythonPresetMethod[];
}

export function emitPythonSdk(program: Program, repoRoot: string): void {
  const outDir = resolvePath(repoRoot, 'python/openbox_sdk/generated');
  const backendNamespace = findNamespace(program, 'OpenboxBackend');
  const methodNames = backendNamespace
    ? getSdkMethodNames(program, backendNamespace) ?? {}
    : {};
  const methodPermissions = backendNamespace
    ? getBackendPermissions(program, backendNamespace) ?? {}
    : {};

  const backendManifest = collectEndpointManifest(program, 'OpenboxBackend', methodNames);
  const coreManifest = collectEndpointManifest(program, 'OpenboxCore', methodNames);
  const governManifest = collectGovernManifest(program);

  rmSync(outDir, { recursive: true, force: true });
  writePythonFile(resolvePath(outDir, '__init__.py'), `${PYTHON_BANNER}__all__: list[str] = []\n`);
  writePythonFile(
    resolvePath(outDir, 'backend_client.py'),
    emitClientModule({
      className: 'BackendOperationsMixin',
      manifestName: 'BACKEND_ENDPOINT_MANIFEST',
      manifest: backendManifest,
    }),
  );
  writePythonFile(
    resolvePath(outDir, 'core_client.py'),
    emitClientModule({
      className: 'CoreOperationsMixin',
      manifestName: 'CORE_ENDPOINT_MANIFEST',
      manifest: coreManifest,
    }),
  );
  writePythonFile(
    resolvePath(outDir, 'permissions.py'),
    emitPermissions(backendManifest, methodPermissions),
  );
  writePythonFile(resolvePath(outDir, 'schemas.py'), emitSchemas(program));
  writePythonFile(resolvePath(outDir, 'capability_matrix.py'), emitCapabilityMatrix(program));
  writePythonFile(resolvePath(outDir, 'sdk_targets.py'), emitSdkTargets(program));
  writePythonFile(resolvePath(outDir, 'govern.py'), emitGovern(governManifest));
  writePythonFile(resolvePath(outDir, 'runtime_contract.py'), emitRuntimeContract(program));
}

function writePythonFile(file: string, content: string): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${content.trimEnd()}\n`);
}

function collectEndpointManifest(
  program: Program,
  namespaceName: string,
  methodNames: Record<string, string>,
): PythonEndpointEntry[] {
  const ns = findNamespace(program, namespaceName);
  if (!ns) return [];
  const [ops] = listHttpOperationsIn(program, ns);
  return ops.map((op) => ({
    operation_id: op.operation.name,
    method_name: methodNameFor(op.operation.name, methodNames),
    verb: op.verb.toLowerCase(),
    path: op.path,
    path_pattern: op.path.replace(/\{[^}]+\}/g, '{x}'),
  }));
}

function methodNameFor(operationId: string, methodNames: Record<string, string>): string {
  const mapped = methodNames[operationId];
  if (mapped) return snakeCase(mapped);
  const suffix = operationId.includes('_')
    ? operationId.split('_').slice(1).join('_')
    : operationId;
  return snakeCase(suffix);
}

function emitClientModule(opts: {
  className: string;
  manifestName: string;
  manifest: PythonEndpointEntry[];
}): string {
  const methods = opts.manifest
    .map((entry) =>
      [
        `    async def ${entry.method_name}(self, *, path_params: JsonMapping | None = None, query: JsonMapping | None = None, data: Any = None) -> Any:`,
        `        path = render_path(${JSON.stringify(entry.path)}, path_params)`,
        `        return await self._request(${JSON.stringify(entry.verb)}, path, params=query, data=data, operation=${JSON.stringify(entry.operation_id)})`,
        '',
      ].join('\n'),
    )
    .join('\n');
  return `${PYTHON_BANNER}from typing import Any, Protocol, TypeAlias

from openbox_sdk._utils import render_path

JsonMapping: TypeAlias = dict[str, Any]

${opts.manifestName} = ${py(opts.manifest)}
OPERATION_TO_ENDPOINT = {entry["operation_id"]: entry for entry in ${opts.manifestName}}
OPERATION_METHOD_NAMES = {entry["operation_id"]: entry["method_name"] for entry in ${opts.manifestName}}
METHOD_OPERATION_NAMES = {entry["method_name"]: entry["operation_id"] for entry in ${opts.manifestName}}


class _Requester(Protocol):
    async def _request(self, method: str, path: str, *, params: JsonMapping | None = None, data: Any = None, operation: str | None = None) -> Any: ...


class ${opts.className}:
    def _resolve_operation(self, operation_id: str, path_params: JsonMapping | None = None) -> tuple[str, str]:
        try:
            entry = OPERATION_TO_ENDPOINT[operation_id]
        except KeyError as exc:
            raise ValueError(f"unknown OpenBox operation_id: {operation_id}") from exc
        return str(entry["verb"]), render_path(str(entry["path"]), path_params)

${methods}`;
}

function emitPermissions(
  manifest: PythonEndpointEntry[],
  permissions: Record<string, string[]>,
): string {
  const rules = [];
  for (const item of manifest) {
    const required = permissions[item.operation_id];
    if (!required || required.length === 0) continue;
    rules.push([
      item.verb,
      regexForPath(item.path_pattern),
      item.method_name,
      required,
    ]);
  }
  return `${PYTHON_BANNER}PATH_PERMISSION_RULES = ${py(rules)}\n`;
}

function emitSchemas(program: Program): string {
  const names = new Set<string>();
  for (const namespaceName of ['OpenboxBackend', 'OpenboxCore']) {
    const ns = findNamespace(program, namespaceName);
    if (ns) collectModelClassNames(ns, names);
  }
  const classes = [...names]
    .map((name) => pythonPascalCase(name))
    .filter(Boolean)
    .sort();
  const uniqueClasses = [...new Set(classes)];
  const classBodies = uniqueClasses
    .map((name) => `class ${name}(OpenBoxGeneratedModel):\n    pass\n`)
    .join('\n\n');
  return `${PYTHON_BANNER}from pydantic import BaseModel, ConfigDict


class OpenBoxGeneratedModel(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)


${classBodies}
__all__ = ${py(['OpenBoxGeneratedModel', ...uniqueClasses])}
`;
}

function collectModelClassNames(ns: Namespace, out: Set<string>): void {
  for (const [name] of ns.models) {
    if (name === 'Array' || name === 'Record') continue;
    if (name) out.add(name);
  }
  for (const child of ns.namespaces.values()) {
    collectModelClassNames(child, out);
  }
}

function emitCapabilityMatrix(program: Program): string {
  const ns = findNamespace(program, 'OpenboxGovern');
  const matrix = ns ? getProviderCapabilities(program, ns) : undefined;
  if (!matrix) {
    return `${PYTHON_BANNER}OPENBOX_CAPABILITY_IDS = []\n`;
  }
  const capabilityIds = arrayOfStrings(matrix.capabilityIds);
  const providers = arrayOfStrings(matrix.providers);
  const supportTiers = uniqueStrings([
    ...arrayOfRecords(matrix.capabilities).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.publicIntegrations).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.goalSignalGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.usageCostCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.tracingCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.hitlCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.guardrailCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.policyEvaluationGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.rulesInstructionCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.hookCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.subagentsAgentsCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.pluginCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.skillCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.mcpCapabilityGuards).map((entry) => String(entry.tier ?? '')),
    ...arrayOfRecords(matrix.installDoctorCapabilityGuards).map((entry) => String(entry.tier ?? '')),
  ]).filter(Boolean);
  return `${PYTHON_BANNER}# Generated from TypeSpec capability contracts.

OPENBOX_CAPABILITY_IDS = ${py(capabilityIds)}
OPENBOX_PROVIDER_IDS = ${py(providers)}
OPENBOX_SUPPORT_TIERS = ${py(supportTiers)}
PROVIDER_CAPABILITY_MATRIX = ${py(matrix.capabilities)}
PROVIDER_EVENT_CATALOG = ${py(matrix.eventCatalog)}
PROVIDER_PLUGIN_COMPONENTS = ${py(matrix.pluginComponents)}
PUBLIC_INTEGRATION_SUPPORT = ${py(matrix.publicIntegrations)}
GOAL_SIGNAL_GUARDS = ${py(matrix.goalSignalGuards)}
USAGE_COST_CAPABILITY_GUARDS = ${py(matrix.usageCostCapabilityGuards)}
TRACING_CAPABILITY_GUARDS = ${py(matrix.tracingCapabilityGuards)}
HITL_CAPABILITY_GUARDS = ${py(matrix.hitlCapabilityGuards)}
GUARDRAIL_CAPABILITY_GUARDS = ${py(matrix.guardrailCapabilityGuards)}
POLICY_EVALUATION_GUARDS = ${py(matrix.policyEvaluationGuards)}
RULES_INSTRUCTION_CAPABILITY_GUARDS = ${py(matrix.rulesInstructionCapabilityGuards)}
HOOK_CAPABILITY_GUARDS = ${py(matrix.hookCapabilityGuards)}
SUBAGENTS_AGENTS_CAPABILITY_GUARDS = ${py(matrix.subagentsAgentsCapabilityGuards)}
PLUGIN_CAPABILITY_GUARDS = ${py(matrix.pluginCapabilityGuards)}
SKILL_CAPABILITY_GUARDS = ${py(matrix.skillCapabilityGuards)}
MCP_CAPABILITY_GUARDS = ${py(matrix.mcpCapabilityGuards)}
INSTALL_DOCTOR_CAPABILITY_GUARDS = ${py(matrix.installDoctorCapabilityGuards)}
MCP_TOOL_SURFACES = ${py(matrix.mcpTools)}
MCP_PROMPT_SURFACES = ${py(matrix.mcpPrompts)}
MCP_RESOURCE_TEMPLATE_SURFACES = ${py(matrix.mcpResourceTemplates)}
MCP_SKILL_REFERENCE_SURFACES = ${py(matrix.mcpSkillReferences)}
N8N_INTEGRATION_SURFACE = ${py(matrix.n8nIntegration)}
`;
}

function emitSdkTargets(program: Program): string {
  const ns = findNamespace(program, 'OpenboxSdk');
  const manifest = ns ? getSdkTargets(program, ns) : undefined;
  if (!manifest) {
    return `${PYTHON_BANNER}SDK_TARGET_MANIFEST = {}\nGENERATED_ARTIFACTS = {}\nCODEGEN_BUILD = {}\nTEST_SUITES = {}\nBUNDLE_BUILD = {}\nPACKAGE_SURFACE = {}\nCLEAN_ARTIFACTS = {}\nSECURITY_AUDIT = {}\nLOCAL_CI = {}\nSDK_TARGETS = []\nSDK_TARGET_IDS = []\n`;
  }
  return `${PYTHON_BANNER}# Generated from TypeSpec SDK target contracts.

SDK_TARGET_MANIFEST = ${py(manifest)}
GENERATED_ARTIFACTS = SDK_TARGET_MANIFEST.get("generatedArtifacts", {})
CODEGEN_BUILD = SDK_TARGET_MANIFEST.get("codegenBuild", {})
TEST_SUITES = SDK_TARGET_MANIFEST.get("testSuites", {})
BUNDLE_BUILD = SDK_TARGET_MANIFEST.get("bundleBuild", {})
PACKAGE_SURFACE = SDK_TARGET_MANIFEST.get("packageSurface", {})
CLEAN_ARTIFACTS = SDK_TARGET_MANIFEST.get("cleanArtifacts", {})
SECURITY_AUDIT = SDK_TARGET_MANIFEST.get("securityAudit", {})
LOCAL_CI = SDK_TARGET_MANIFEST.get("localCi", {})
SDK_TARGETS = SDK_TARGET_MANIFEST.get("targets", [])
SDK_TARGET_IDS = [target["id"] for target in SDK_TARGETS]

__all__ = ["SDK_TARGET_MANIFEST", "GENERATED_ARTIFACTS", "CODEGEN_BUILD", "TEST_SUITES", "BUNDLE_BUILD", "PACKAGE_SURFACE", "CLEAN_ARTIFACTS", "SECURITY_AUDIT", "LOCAL_CI", "SDK_TARGETS", "SDK_TARGET_IDS"]
`;
}

function collectGovernManifest(program: Program): PythonPresetEntry[] {
  const ns = findNamespace(program, 'OpenboxGovern');
  if (!ns) return [];
  const presets: PythonPresetEntry[] = [];
  for (const [, iface] of ns.interfaces) {
    const preset = getPreset(program, iface);
    if (!preset) continue;
    const isCustom = preset.name === 'custom';
    const methods: PythonPresetMethod[] = [];
    for (const [opName, op] of iface.operations) {
      if (isCustom) {
        methods.push({ name: opName });
        continue;
      }
      const mapping = getMapsTo(program, op);
      if (!mapping) continue;
      methods.push({
        name: opName,
        eventType: mapping.eventType,
        activityType: mapping.activityType ?? opName,
      });
    }
    if (methods.length > 0) {
      presets.push({ preset: preset.name, methods });
    }
  }
  return presets.sort((a, b) => a.preset.localeCompare(b.preset));
}

function emitGovern(governManifest: PythonPresetEntry[]): string {
  const classes = [];
  const registry = [];
  const presetActivityTypes: Record<string, Record<string, string>> = {};
  for (const preset of governManifest) {
    const className = `${pythonPascalCase(preset.preset)}Session`;
    const presetKey = snakeCase(preset.preset);
    registry.push([presetKey, className]);
    presetActivityTypes[preset.preset] = Object.fromEntries(
      preset.methods.flatMap((method) =>
        method.activityType ? [[method.name, method.activityType]] : [],
      ),
    );
    if (presetKey === 'custom') {
      classes.push([
        `class ${className}(BaseGovernedSession):`,
        `    async def activity(self, activity_type: str, stage: ActivityStage, payload: GovernedPayload | None = None) -> WorkflowVerdict:`,
        `        event_type = "ActivityStarted" if stage == "pre" else "ActivityCompleted"`,
        `        return await self.run_activity(event_type, activity_type, payload or {})`,
        '',
      ].join('\n'));
      continue;
    }
    const methods = preset.methods
      .map((method) => {
        const methodName = snakeCase(method.name);
        return [
          `    async def ${methodName}(self, payload: GovernedPayload | None = None) -> WorkflowVerdict:`,
          `        return await self.run_activity(${JSON.stringify(method.eventType)}, ${JSON.stringify(method.activityType)}, payload or {})`,
          '',
        ].join('\n');
      })
      .join('\n');
    classes.push(`class ${className}(BaseGovernedSession):\n${methods || '    pass\n'}`);
  }
  const registryLiteral = `{\n${registry.map(([key, cls]) => `    ${JSON.stringify(key)}: ${cls},`).join('\n')}\n}`;
  return `${PYTHON_BANNER}from types import SimpleNamespace

from openbox_sdk._govern_runtime import ActivityStage, BaseGovernedSession, GovernedPayload, WorkflowVerdict

PRESET_MANIFEST = ${py(governManifest)}
PRESET_ACTIVITY_TYPES = ${py(presetActivityTypes)}


${classes.join('\n\n')}

PRESET_CLASSES = ${registryLiteral}
presets = SimpleNamespace(**PRESET_CLASSES)

__all__ = ["PRESET_MANIFEST", "PRESET_ACTIVITY_TYPES", "PRESET_CLASSES", "presets", ${registry.map(([, cls]) => JSON.stringify(cls)).join(', ')}]
`;
}

function emitRuntimeContract(program: Program): string {
  const core = findNamespace(program, 'OpenboxCore');
  const govern = findNamespace(program, 'OpenboxGovern');
  if (!core || !govern) return `${PYTHON_BANNER}`;

  const verdictArms = enumValues(govern, 'VerdictArm');
  const eventTypes = enumValues(core, 'EventType');
  const guardrailsVerdict = requireModel(govern, 'GuardrailsVerdict');
  const guardrailFieldVerdict = requireModel(govern, 'GuardrailFieldVerdict');
  const governedPayload = requireModel(govern, 'GovernedPayload');
  const workflowVerdict = requireModel(govern, 'WorkflowVerdict');
  const governanceEventPayload = requireModel(core, 'GovernanceEventPayload');
  const governanceVerdictResponse = requireModel(core, 'GovernanceVerdictResponse');
  const guardrailsResult = requireModel(core, 'GuardrailsResult');
  const approvalStatusResponse = requireModel(core, 'ApprovalStatusResponse');
  const spanData = requireModel(core, 'SpanData');

  const guardrailInputTypes = propertyStringLiterals(guardrailsVerdict, 'inputType');
  const guardrailFieldStatuses = propertyStringLiterals(guardrailFieldVerdict, 'status');
  const hookParentEventTypes = propertyStringLiterals(
    governedPayload,
    'hookSpanParentEventType',
  );
  const eventTypeConstants = Object.entries(
    Object.fromEntries(eventTypes.map((value) => [eventTypeConstantName(value), value])),
  )
    .map(([name, value]) => `${name} = ${py(value)}`)
    .join('\n');

  requireValue(eventTypes, 'ActivityStarted', 'EventType');
  requireValue(eventTypes, 'ActivityCompleted', 'EventType');
  const defaultGuardrailInputType = requireValue(
    guardrailInputTypes,
    'activity_input',
    'GuardrailsVerdict.inputType',
  );
  const guardrailOutputType = requireValue(
    guardrailInputTypes,
    'activity_output',
    'GuardrailsVerdict.inputType',
  );
  const defaultGuardrailFieldStatus = requireValue(
    guardrailFieldStatuses,
    'skipped',
    'GuardrailFieldVerdict.status',
  );
  const guardrailRedactionStatuses = requireValues(
    guardrailFieldStatuses,
    ['redacted', 'transformed'],
    'GuardrailFieldVerdict.status',
  );

  const telemetryFieldAliases = [
    ['session_id', 'sessionId'],
    ['llm_model', 'llmModel'],
    ['input_tokens', 'inputTokens'],
    ['output_tokens', 'outputTokens'],
    ['total_tokens', 'totalTokens'],
    ['has_tool_calls', 'hasToolCalls'],
    ['finish_reason', 'finishReason'],
    ['prompt', 'prompt'],
    ['completion', 'completion'],
    ['tool_name', 'toolName'],
    ['tool_type', 'toolType'],
    ['parent_run_id', 'parentRunId'],
    ['multi_agent_session_id', 'multiAgentSessionId'],
    ['from_agent_did', 'fromAgentDid'],
  ] as const;
  const governanceEventFields = modelPropertyNames(governanceEventPayload);
  const governedPayloadFields = modelPropertyNames(governedPayload);
  assertSubset(
    telemetryFieldAliases.map(([snake]) => snake),
    governanceEventFields,
    'TELEMETRY_FIELD_ALIASES core side',
  );
  assertSubset(
    telemetryFieldAliases.map(([, camel]) => camel),
    governedPayloadFields,
    'TELEMETRY_FIELD_ALIASES governed side',
  );

  const governedPayloadFieldAliases = validatedAliasMap(
    [
      { target: 'activity_id', core: 'activity_id', govern: 'activityId' },
      { target: 'start_time', core: 'start_time', govern: 'startTime' },
      { target: 'end_time', core: 'end_time', govern: 'endTime' },
      { target: 'duration_ms', core: 'duration_ms', govern: 'durationMs' },
      { target: 'signal_name', core: 'signal_name', govern: 'signalName' },
      { target: 'signal_args', core: 'signal_args', govern: 'signalArgs' },
      {
        target: 'hook_span_parent_event_type',
        govern: 'hookSpanParentEventType',
        extra: 'hook_span_parent_event_type',
      },
      {
        target: 'ensure_hook_span_parent',
        govern: 'ensureHookSpanParent',
        extra: 'ensure_hook_span_parent',
      },
    ],
    [
      { name: 'core', fields: governanceEventFields },
      { name: 'govern', fields: governedPayloadFields },
    ],
    'GOVERNED_PAYLOAD_FIELD_ALIASES',
  );
  const workflowVerdictFieldAliases = validatedAliasMap(
    [
      { target: 'arm', core: ['verdict', 'action'], govern: 'arm' },
      { target: 'approvalId', core: 'approval_id', govern: 'approvalId' },
      {
        target: 'governanceEventId',
        core: 'governance_event_id',
        govern: 'governanceEventId',
      },
      {
        target: 'approvalExpiresAt',
        core: 'approval_expiration_time',
        govern: 'approvalExpiresAt',
      },
      { target: 'reason', core: 'reason', govern: 'reason' },
      { target: 'riskScore', core: 'risk_score', govern: 'riskScore' },
      { target: 'trustTier', core: 'trust_tier', govern: 'trustTier' },
      { target: 'alignmentScore', core: 'alignment_score', govern: 'alignmentScore' },
      { target: 'policyId', core: 'policy_id', govern: 'policyId' },
      {
        target: 'behavioralViolations',
        core: 'behavioral_violations',
        govern: 'behavioralViolations',
      },
      { target: 'fallbackUsed', core: 'fallback_used', govern: 'fallbackUsed' },
      { target: 'guardrailsResult', core: 'guardrails_result', govern: 'guardrailsResult' },
      { target: 'ageResult', core: 'age_result', govern: 'ageResult' },
    ],
    [
      { name: 'core', fields: modelPropertyNames(governanceVerdictResponse) },
      { name: 'govern', fields: modelPropertyNames(workflowVerdict) },
    ],
    'WORKFLOW_VERDICT_FIELD_ALIASES',
  );
  const guardrailsResultFieldAliases = validatedAliasMap(
    [
      { target: 'inputType', core: 'input_type', govern: 'inputType' },
      { target: 'redactedInput', core: 'redacted_input', govern: 'redactedInput' },
      { target: 'redactedOutput', core: 'redacted_output', govern: 'redactedOutput' },
      { target: 'validationPassed', core: 'validation_passed', govern: 'validationPassed' },
      { target: 'rawLogs', core: 'raw_logs', govern: 'rawLogs' },
      { target: 'reasons', core: 'reasons', govern: 'reasons' },
      { target: 'fieldResults', core: 'field_results', govern: 'fieldResults' },
    ],
    [
      { name: 'core', fields: modelPropertyNames(guardrailsResult) },
      { name: 'govern', fields: modelPropertyNames(guardrailsVerdict) },
    ],
    'GUARDRAILS_RESULT_FIELD_ALIASES',
  );
  const approvalStatusFieldAliases = validatedAliasMap(
    [
      { target: 'arm', core: 'action', extra: 'verdict' },
      { target: 'approvalExpiresAt', core: 'approval_expiration_time', extra: 'approvalExpiresAt' },
      { target: 'reason', core: 'reason' },
    ],
    [{ name: 'core', fields: modelPropertyNames(approvalStatusResponse) }],
    'APPROVAL_STATUS_FIELD_ALIASES',
  );
  assertSubset(
    ['verdict'],
    modelPropertyNames(governanceVerdictResponse),
    'APPROVAL_STATUS_FIELD_ALIASES arm fallback',
  );
  const spanAliasSnakeFields = [
    'span_id',
    'trace_id',
    'parent_span_id',
    'start_time',
    'end_time',
    'duration_ns',
    'semantic_type',
    'hook_type',
    'request_body',
    'response_body',
    'request_headers',
    'response_headers',
  ];
  assertSubset(spanAliasSnakeFields, modelPropertyNames(spanData), 'SPAN_ALIAS_FIELDS');
  const spanRootStringFields = [
    'semantic_type',
    'hook_type',
    'http_url',
    'http_method',
    'file_path',
    'file_operation',
    'db_statement',
    'db_operation',
    'db_system',
  ];
  assertSubset(
    spanRootStringFields,
    modelPropertyNames(spanData),
    'SPAN_PERSISTABLE_ROOT_STRING_FIELDS',
  );
  const runtimeHintCamelFields = ['hookSpanParentEventType', 'ensureHookSpanParent'];
  assertSubset(runtimeHintCamelFields, governedPayloadFields, 'SPAN_RUNTIME_HINT_FIELDS');
  const runtimeHintFields = runtimeHintCamelFields.flatMap((field) => [
    field.replace(/[A-Z]/g, (char) => `_${char.toLowerCase()}`),
    field,
  ]);
  return `${PYTHON_BANNER}# Generated from TypeSpec governance/core contract inputs.

EVENT_TYPES = ${py(eventTypes)}
${eventTypeConstants}
VERDICT_ARMS = ${py(verdictArms)}
VERDICT_ARM_RANK = ${py(Object.fromEntries(verdictArms.map((arm, index) => [arm, index])))}
GUARDRAIL_INPUT_TYPES = ${py(guardrailInputTypes)}
DEFAULT_GUARDRAIL_INPUT_TYPE = ${py(defaultGuardrailInputType)}
GUARDRAIL_INPUT_LIKE_TYPES = ${py(guardrailInputTypes.filter((value) => value !== guardrailOutputType))}
GUARDRAIL_OUTPUT_TYPE = ${py(guardrailOutputType)}
GUARDRAIL_FIELD_STATUSES = ${py(guardrailFieldStatuses)}
DEFAULT_GUARDRAIL_FIELD_STATUS = ${py(defaultGuardrailFieldStatus)}
GUARDRAIL_REDACTION_STATUSES = ${py(guardrailRedactionStatuses)}
HOOK_SPAN_PARENT_EVENT_TYPES = ${py(hookParentEventTypes)}
DEFAULT_HOOK_SPAN_PARENT_EVENT_TYPE = ${py(hookParentEventTypes[0] || null)}
GOVERNED_PAYLOAD_FIELD_ALIASES = ${py(governedPayloadFieldAliases)}
WORKFLOW_VERDICT_FIELD_ALIASES = ${py(workflowVerdictFieldAliases)}
GUARDRAILS_RESULT_RESPONSE_ALIASES = ${py(workflowVerdictFieldAliases.guardrailsResult)}
GUARDRAILS_RESULT_FIELD_ALIASES = ${py(guardrailsResultFieldAliases)}
APPROVAL_STATUS_FIELD_ALIASES = ${py(approvalStatusFieldAliases)}
APPROVAL_EXPIRY_ALIASES = ${py(uniqueStrings([...approvalStatusFieldAliases.approvalExpiresAt, 'expires_at', 'expiresAt']))}
TELEMETRY_FIELD_ALIASES = ${py(Object.fromEntries(telemetryFieldAliases.map(([snake, camel]) => [snake, [snake, camel]])))}
SPAN_ALIAS_FIELDS = ${py(spanAliasSnakeFields.map((field) => [field, snakeToCamel(field)]))}
SPAN_PERSISTABLE_ROOT_STRING_FIELDS = ${py(spanRootStringFields)}
SPAN_PERSISTABLE_ATTRIBUTE_FIELDS = ${py(['url.full', 'http.url', 'http.method', 'file.path', 'file.operation', 'db.statement', 'db.operation', 'db.system', 'shell.command', 'mcp.method', 'openbox.tool.name', 'tool.name', 'tool_name', 'gen_ai.system'])}
SPAN_RUNTIME_HINT_FIELDS = ${py(runtimeHintFields)}
SPAN_STATUS_CODES = ${py(propertyStringLiterals(requireModel(core, 'SpanStatus'), 'code'))}
`;
}

function requireModel(ns: Namespace, name: string): Model {
  const model = ns.models.get(name);
  if (!model) throw new Error(`Missing TypeSpec model ${ns.name}.${name}`);
  return model;
}

function enumValues(ns: Namespace, name: string): string[] {
  const enumType = ns.enums.get(name);
  if (!enumType) throw new Error(`Missing TypeSpec enum ${ns.name}.${name}`);
  return [...enumType.members.values()].map((member) => String(member.value ?? member.name));
}

function modelPropertyNames(model: Model): string[] {
  return [...model.properties.keys()];
}

function propertyStringLiterals(model: Model, propertyName: string): string[] {
  const property = model.properties.get(propertyName);
  if (!property) throw new Error(`Missing TypeSpec property ${model.name}.${propertyName}`);
  return stringLiteralsFromType(property.type);
}

function stringLiteralsFromType(type: Type): string[] {
  switch (type.kind) {
    case 'String':
      return [String(type.value)];
    case 'Enum':
      return [...type.members.values()].map((member) => String(member.value ?? member.name));
    case 'Union':
      return [...type.variants.values()].flatMap((variant) =>
        stringLiteralsFromType(variant.type),
      );
    default:
      return [];
  }
}

function validatedAliasMap(
  entries: Array<Record<string, unknown> & { target: string }>,
  fieldGroups: Array<{ name: string; fields: string[] }>,
  label: string,
): Record<string, string[]> {
  const byGroup = Object.fromEntries(fieldGroups.map((group) => [group.name, group.fields]));
  const result: Record<string, string[]> = {};
  for (const entry of entries) {
    const aliases: string[] = [];
    for (const groupName of Object.keys(byGroup)) {
      const values = asArray(entry[groupName]);
      assertSubset(values, byGroup[groupName], `${label}.${entry.target} ${groupName}`);
      aliases.push(...values);
    }
    aliases.push(...asArray(entry.extra));
    result[entry.target] = uniqueStrings(aliases);
  }
  return result;
}

function assertSubset(values: string[], allowed: string[], label: string): void {
  const missing = values.filter((value) => !allowed.includes(value));
  if (missing.length > 0) {
    throw new Error(`${label} references fields not present in TypeSpec: ${missing.join(', ')}`);
  }
}

function requireValue(values: string[], expected: string, label: string): string {
  if (!values.includes(expected)) {
    throw new Error(`${label} is missing expected value ${expected}`);
  }
  return expected;
}

function requireValues(values: string[], expected: string[], label: string): string[] {
  for (const value of expected) {
    requireValue(values, value, label);
  }
  return expected;
}

function asArray(value: unknown): string[] {
  if (value === undefined || value === null) return [];
  return Array.isArray(value) ? value.map(String) : [String(value)];
}

function arrayOfStrings(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((entry): entry is string => typeof entry === 'string')
    : [];
}

function arrayOfRecords(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value)
    ? value.filter(
        (entry): entry is Record<string, unknown> =>
          entry !== null && typeof entry === 'object' && !Array.isArray(entry),
      )
    : [];
}

function uniqueStrings(values: string[]): string[] {
  return [...new Set(values.filter((value) => value !== undefined && value !== null))];
}

function snakeCase(name: string): string {
  const value = name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
  if (!value) return 'operation';
  return PYTHON_KEYWORDS.has(value) ? `${value}_` : value;
}

function pythonPascalCase(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function regexForPath(pathPattern: string): string {
  const escaped = pathPattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `^${escaped.replace(/\\\{[^/]+\\\}/g, '[^/]+')}$`;
}

function eventTypeConstantName(value: string): string {
  return `${value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase()}_EVENT_TYPE`;
}

function snakeToCamel(value: string): string {
  return value.replace(/_([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

function py(value: unknown, indent = 0): string {
  const pad = ' '.repeat(indent);
  const childPad = ' '.repeat(indent + 2);
  if (value === null || value === undefined) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map((item) => `${childPad}${py(item, indent + 2)}`).join(',\n')}\n${pad}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entry]) => entry !== undefined);
    if (entries.length === 0) return '{}';
    return `{\n${entries
      .map(([key, entry]) => `${childPad}${JSON.stringify(key)}: ${py(entry, indent + 2)}`)
      .join(',\n')}\n${pad}}`;
  }
  return 'None';
}

function findNamespace(program: Program, name: string): Namespace | undefined {
  if (name.includes('.')) {
    const parts = name.split('.');
    let cur: Namespace | undefined = program.getGlobalNamespaceType();
    for (const part of parts) {
      if (!cur) return undefined;
      cur = cur.namespaces.get(part);
    }
    return cur;
  }
  const stack = [program.getGlobalNamespaceType()];
  while (stack.length) {
    const ns = stack.pop()!;
    if (ns.name === name) return ns;
    for (const sub of ns.namespaces.values()) stack.push(sub);
  }
  return undefined;
}
