// TypeSpec → TypeScript emitter for the OpenBox SDK monorepo.
//
// Each emit*() function targets one workspace package under ts/. The
// outputs land in `<package>/src/generated/` and are wired into the
// hand-written index via re-export. We never overwrite hand-written
// code; all generated files start with a `// AUTO-GENERATED` banner
// and live in their own subdir so a `git status` makes drift obvious.
//
// The emitter is pulled in via `tspconfig.yaml`'s emitter list
// alongside @typespec/openapi3 - same compile pass, separate output
// dirs.

import { readFileSync } from 'fs';
import { Project, IndentationText, NewLineKind, QuoteKind } from 'ts-morph';
import type {
  EmitContext,
  Interface,
  Model,
  Namespace,
  Operation,
  Program,
  Type,
} from '@typespec/compiler';
import { resolvePath } from '@typespec/compiler';
import { listHttpOperationsIn } from '@typespec/http';
import { getEnvVar, getTokenFormat, isOsPath } from '@openbox/typespec-env/decorators';
import { getCommand, getFlag } from '@openbox/typespec-cli/decorators';
import {
  getMapsTo,
  getPreset,
  isVerdict,
  getAdapter,
  getHookEvent,
  getVerdictShape,
  type CanonicalEventType,
  type VerdictShape,
} from '@openbox/typespec-workflow/decorators';

const BANNER = `// AUTO-GENERATED by codegen/emitters/ts. DO NOT EDIT.
// Regenerate with: npm run specs:compile
`;

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const repoRoot = resolveRepoRoot(context);
  const project = newTsMorphProject();

  emitEnvPackage(program, project, repoRoot);
  emitCliPackage(program, project, repoRoot);
  emitEndpointManifest(program, project, repoRoot, 'OpenboxBackend', 'BACKEND_ENDPOINT_MANIFEST', 'ts/client/src/generated/endpoint-manifest.ts');
  emitEndpointManifest(program, project, repoRoot, 'OpenboxCore', 'CORE_ENDPOINT_MANIFEST', 'ts/core-client/src/generated/endpoint-manifest.ts');
  emitNamespaceTypes(program, project, repoRoot, 'OpenboxCore', 'ts/core-client/src/generated/core-types.ts');
  emitGovernProtocol(program, project, repoRoot);
  emitAdapters(program, project, repoRoot);
  emitWrapperMethods(program, project, repoRoot, {
    namespaceName: 'OpenboxBackend',
    outRel: 'ts/client/src/generated/wrapper-methods.ts',
    pathsImport: '@openbox/types',
    pathsAlias: 'Backend',
    className: 'OpenBoxClientWrapperBase',
    emitPermissions: true,
  });
  emitWrapperMethods(program, project, repoRoot, {
    namespaceName: 'OpenboxCore',
    outRel: 'ts/core-client/src/generated/wrapper-methods.ts',
    pathsImport: '@openbox/types',
    pathsAlias: 'Core',
    className: 'OpenBoxCoreClientWrapperBase',
  });

  await project.save();
}

// ---------------------------------------------------------------------------
// HTTP wrapper-method body emit
// ---------------------------------------------------------------------------
//
// For each endpoint declared on the namespace, generate a method body of
// the form `this.<verb>(<path>, <body>?, <opts>?)`. The hand-written
// wrapper class (OpenBoxClient / OpenBoxCoreClient) extends the
// generated `<Service>WrapperBase` to inherit all the wire methods.
// Adds 130+ methods to OpenBoxClient and 4 to OpenBoxCoreClient
// without a code edit.

interface WrapperMethodSpec {
  name: string;
  verb: string; // get / post / put / patch / delete
  pathTemplate: string; // backtick-template form with ${arg} placeholders
  pathParams: { name: string; tsType: string }[];
  bodyParam: { name: string; tsType: string } | null;
  queryParam: { name: string; tsType: string } | null;
  responseTsType: string;
  /** Required permissions (from method-permissions.json). Empty array
   *  if the operation has no @Permissions(...) decorator. */
  requiredPermissions: string[];
}

interface WrapperEmitOptions {
  namespaceName: string;
  outRel: string;
  pathsImport: string; // e.g. '@openbox/types'
  pathsAlias: string; // 'Backend' | 'Core' - namespace re-export alias
  className: string;
  /**
   * If true, emit METHOD_PERMISSIONS + MissingPermissionError and wire
   * a pre-flight `checkPermissions(methodName)` into every generated
   * method body. Backend wrapper only - core uses API keys, no perm
   * check needed. The hand-written subclass populates `this.permissions`
   * from `BackendClientConfig.permissions` if the consumer provides it.
   */
  emitPermissions?: boolean;
}

function emitWrapperMethods(
  program: Program,
  project: Project,
  repoRoot: string,
  opts: WrapperEmitOptions,
): void {
  const ns = findNamespace(program, opts.namespaceName);
  if (!ns) return;

  const [ops] = listHttpOperationsIn(program, ns);
  if (ops.length === 0) return;

  const methods: WrapperMethodSpec[] = [];
  const seen = new Set<string>();
  for (const op of ops) {
    const spec = wrapperMethodFor(op);
    if (!spec) continue;
    // Dedup by method name in case operationIds collide after stripping
    // the controller prefix.
    if (seen.has(spec.name)) continue;
    seen.add(spec.name);
    methods.push(spec);
  }

  if (methods.length === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, opts.outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  out.addStatements(emitWrapperBaseClass(opts, methods));
}

type HttpOp = ReturnType<typeof listHttpOperationsIn>[0][number];

// Curated operationId → methodName map. Avoids collisions when multiple
// controllers share a verb (e.g. AgentController_list, ApiKeyController_list,
// WebhookController_list, MemberController_list all map to a unique
// `listAgents` / `listApiKeys` / `listWebhooks` / `getMembers`). Lives in
// codegen/method-names.json as a hand-curated artifact so consumers across
// languages can converge on the same names.
let CURATED_METHOD_NAMES: Record<string, string> = {};
try {
  const raw = readFileSync(resolvePath(process.cwd(), 'codegen/method-names.json'), 'utf8');
  CURATED_METHOD_NAMES = JSON.parse(raw);
} catch {
  // First-run before the file exists; emitter falls back to the bare
  // operationId-stripping heuristic below.
}

// operationId → required permissions. Extracted from backend NestJS
// controllers' @Permissions(PermissionEnum.X) decorators by
// scripts/extract-perms.mjs. Drives the generated pre-flight check on
// the backend wrapper class.
let METHOD_PERMISSIONS_MAP: Record<string, string[]> = {};
try {
  const raw = readFileSync(
    resolvePath(process.cwd(), 'codegen/method-permissions.json'),
    'utf8',
  );
  METHOD_PERMISSIONS_MAP = JSON.parse(raw);
} catch {
  // Permissions file is optional - pre-flight degrades to a no-op.
}

function wrapperMethodFor(op: HttpOp): WrapperMethodSpec | null {
  const opId = op.operation.name;
  let methodName: string;
  if (CURATED_METHOD_NAMES[opId]) {
    methodName = CURATED_METHOD_NAMES[opId];
  } else {
    // Fallback heuristic: strip the `<Tag>Controller_` prefix. Used only
    // for new ops that haven't been added to method-names.json yet - they
    // get the bare verb (e.g. `list`) and may collide; the next manual
    // run of `node /tmp/build-name-map.mjs` (or hand-edit) curates a name.
    methodName = opId;
    const m = opId.match(/^([A-Z][a-zA-Z]*Controller)_(.+)$/);
    if (m) methodName = m[2];
  }

  const pathParams: { name: string; tsType: string }[] = [];
  let bodyParam: { name: string; tsType: string } | null = null;
  let queryParam: { name: string; tsType: string } | null = null;

  for (const p of op.parameters.parameters) {
    if (p.type === 'path') {
      pathParams.push({ name: p.name, tsType: tspTypeToTs(p.param.type) });
    } else if (p.type === 'query') {
      // Multiple query params get flattened by callers via a single options
      // bag; surface as `Record<string, unknown>` for now (the openapi-typescript
      // -typed helpers in the hand-written wrapper coerce it back to the right shape).
      queryParam = { name: 'query', tsType: 'Record<string, unknown>' };
    }
  }

  if (op.parameters.body && 'type' in op.parameters.body && op.parameters.body.type) {
    bodyParam = { name: 'body', tsType: tspTypeToTs(op.parameters.body.type) };
  }

  // Response - pick the first 2xx body if any.
  let responseTsType = 'unknown';
  for (const r of op.responses) {
    const status =
      typeof r.statusCodes === 'number'
        ? r.statusCodes
        : typeof r.statusCodes === 'object' && r.statusCodes !== null
          ? r.statusCodes.start
          : 0;
    if (status >= 200 && status < 300) {
      for (const content of r.responses) {
        if (content.body && 'type' in content.body && content.body.type) {
          responseTsType = tspTypeToTs(content.body.type);
          break;
        }
      }
      break;
    }
  }

  // Build a backtick-template path: `/agent/${agentId}/guardrails`
  let pathTemplate = op.path;
  for (const p of pathParams) {
    pathTemplate = pathTemplate.replace(`{${p.name}}`, `\${${p.name}}`);
  }

  return {
    name: methodName,
    verb: op.verb.toLowerCase(),
    pathTemplate,
    pathParams,
    bodyParam,
    queryParam,
    responseTsType,
    requiredPermissions: METHOD_PERMISSIONS_MAP[opId] ?? [],
  };
}

function emitWrapperBaseClass(opts: WrapperEmitOptions, methods: WrapperMethodSpec[]): string[] {
  // Helper-fn name per verb. `delete` is reserved → `del` in our wrappers.
  // Helpers are namespaced with `http` prefix to avoid clashing with
  // method names that also start with `get` / `post` / etc. (e.g.
  // `getProfile`, `postEvent`). TypeScript would otherwise read those
  // as overloads of the abstract base method.
  const verbToHelper: Record<string, string> = {
    get: 'httpGet',
    post: 'httpPost',
    put: 'httpPut',
    patch: 'httpPatch',
    delete: 'httpDelete',
  };

  const lines: string[] = [];

  // Import the openapi-typescript output once at the top so every
  // method's response type can be expressed via indexed access:
  //
  //   Backend.paths['/auth/profile']['get']['responses']['200']['content']['application/json']
  //
  // This sidesteps the "PaginatedResponse<T> inlining" problem - we
  // never need a named alias for the generic instantiation; the
  // openapi-typescript path object already has the structural type.
  lines.push(`import type { ${opts.pathsAlias} } from '${opts.pathsImport}';`);
  lines.push('');

  if (opts.emitPermissions) {
    // Emit METHOD_PERMISSIONS (by methodName, for tooling) and
    // PATH_PERMISSION_RULES (by verb+path-template, for runtime check).
    // The runtime check uses path templates because http* helpers see
    // realized paths like `/agent/abc-123/guardrails`, not the spec
    // template `/agent/{agentId}/guardrails`.
    const methodsWithPerms = methods.filter((m) => m.requiredPermissions.length > 0);
    const permsEntries: Array<[string, string[]]> = methodsWithPerms
      .map((m) => [m.name, [...m.requiredPermissions].sort()]);
    permsEntries.sort(([a], [b]) => a.localeCompare(b));

    lines.push(`/**`);
    lines.push(` * Permission requirements per method, extracted from backend NestJS`);
    lines.push(` * controllers' @Permissions(PermissionEnum.X) decorators. Methods`);
    lines.push(` * absent from this map have no @Permissions decorator (public or`);
    lines.push(` * api-key-gated endpoints). Source: codegen/method-permissions.json.`);
    lines.push(` */`);
    lines.push(`export const METHOD_PERMISSIONS: Record<string, readonly string[]> = {`);
    for (const [name, perms] of permsEntries) {
      lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(perms)},`);
    }
    lines.push(`};`);
    lines.push('');

    lines.push(`/**`);
    lines.push(` * Path-template rules used by the runtime pre-flight check inside`);
    lines.push(` * \`request()\`. Each rule's pattern matches the realized path the`);
    lines.push(` * http* helpers receive. Order matches spec declaration; the rule`);
    lines.push(` * lookup is first-match-wins, which is unambiguous because path`);
    lines.push(` * templates are non-overlapping per (verb, path).`);
    lines.push(` */`);
    lines.push(`interface PathPermissionRule {`);
    lines.push(`  verb: string;`);
    lines.push(`  pattern: RegExp;`);
    lines.push(`  methodName: string;`);
    lines.push(`  perms: readonly string[];`);
    lines.push(`}`);
    lines.push('');
    lines.push(`export const PATH_PERMISSION_RULES: readonly PathPermissionRule[] = [`);
    // Sort by descending path specificity so longer literal paths match
    // before catch-all parametric ones (e.g. /agent/list before
    // /agent/{agentId}). Counting non-parametric segment chars works.
    const rulesSorted = [...methodsWithPerms].sort((a, b) => {
      const score = (m: WrapperMethodSpec) =>
        m.pathTemplate.replace(/\$\{[^}]+\}/g, '').length;
      return score(b) - score(a);
    });
    for (const m of rulesSorted) {
      const specPath = m.pathTemplate.replace(/\$\{([^}]+)\}/g, '{$1}');
      // Build a regex from the spec path: escape regex chars, replace
      // {param} with [^/]+, anchor with ^…$.
      const pattern = pathTemplateToRegex(specPath);
      lines.push(`  {`);
      lines.push(`    verb: ${JSON.stringify(m.verb.toUpperCase())},`);
      lines.push(`    pattern: ${pattern},`);
      lines.push(`    methodName: ${JSON.stringify(m.name)},`);
      lines.push(`    perms: ${JSON.stringify([...m.requiredPermissions].sort())},`);
      lines.push(`  },`);
    }
    lines.push(`];`);
    lines.push('');

    lines.push(`/**`);
    lines.push(` * Thrown by the wrapper's pre-flight check when the caller's cached`);
    lines.push(` * permission set doesn't cover the method's @Permissions requirements.`);
    lines.push(` * Saves a round-trip + a 403 from the server.`);
    lines.push(` */`);
    lines.push(`export class MissingPermissionError extends Error {`);
    lines.push(`  constructor(`);
    lines.push(`    public readonly methodName: string,`);
    lines.push(`    public readonly missing: readonly string[],`);
    lines.push(`    public readonly have: readonly string[],`);
    lines.push(`  ) {`);
    lines.push(`    super(`);
    lines.push(
      `      \`[\${methodName}] missing permissions: \${missing.join(', ')}. \` +`,
    );
    lines.push(`      \`Have: \${have.length ? have.join(', ') : '(none)'}. \` +`);
    lines.push(`      \`Run \\\`openbox auth refresh\\\` if your token was just upgraded.\``);
    lines.push(`    );`);
    lines.push(`    this.name = 'MissingPermissionError';`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push('');
  }


  // Path -> verb -> argument shape derived from `paths`. Each
  // method below references these via indexed access so changes to
  // the spec flow through openapi-typescript regen automatically.
  lines.push(`type Paths = ${opts.pathsAlias}.paths;`);
  lines.push(`type RequestBodyOf<P extends keyof Paths, V extends keyof Paths[P]> =`);
  lines.push(
    `  Paths[P][V] extends { requestBody?: { content: { 'application/json': infer B } } } ? B : never;`,
  );
  lines.push(`type ResponseOf<P extends keyof Paths, V extends keyof Paths[P]> =`);
  lines.push(
    `  Paths[P][V] extends { responses: infer R } ? R extends Record<200 | 201, { content: { 'application/json': infer J } }> ? J : R extends Record<200 | 201, infer N> ? (N extends { description?: string } ? unknown : never) : unknown : unknown;`,
  );
  lines.push('');

  lines.push(`/**`);
  lines.push(
    ` * AUTO-GENERATED wrapper base class - every HTTP operation declared on`,
  );
  lines.push(` * the ${opts.namespaceName} TypeSpec namespace becomes a typed method here.`);
  lines.push(` * Hand-written wrappers (OpenBoxClient / OpenBoxCoreClient) extend this`);
  lines.push(` * class and own construction + the protected helper methods that the`);
  lines.push(` * generated bodies call into. Adding/removing/renaming an endpoint in`);
  lines.push(` * the spec flows through here without a code edit on the impl side.`);
  lines.push(` */`);
  lines.push(`export abstract class ${opts.className} {`);
  // Helpers exposed by the hand-written wrapper. The `http` prefix
  // avoids name clashes with API methods like `getProfile` / `postEvent`.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lines.push(`  protected abstract httpGet<T>(path: string, query?: any): Promise<T>;`);
  lines.push(`  protected abstract httpPost<T>(path: string, body?: unknown): Promise<T>;`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lines.push(`  protected abstract httpPut<T>(path: string, body?: unknown, query?: any): Promise<T>;`);
  lines.push(`  protected abstract httpPatch<T>(path: string, body?: unknown): Promise<T>;`);
  lines.push(`  protected abstract httpDelete<T>(path: string, body?: unknown): Promise<T>;`);
  lines.push('');

  if (opts.emitPermissions) {
    lines.push(`  /**`);
    lines.push(`   * Cached permission set. When undefined, pre-flight checks are`);
    lines.push(`   * skipped - the SDK behaves as before, deferring to the server's`);
    lines.push(`   * 403 response. The hand-written wrapper populates this from`);
    lines.push(`   * \`BackendClientConfig.permissions\` if the caller provides it.`);
    lines.push(`   */`);
    lines.push(`  protected permissions?: ReadonlySet<string>;`);
    lines.push('');
    lines.push(`  /**`);
    lines.push(`   * Pre-flight permission check. Called by the hand-written`);
    lines.push(`   * \`request()\` impl on every outbound HTTP - covers both generated`);
    lines.push(`   * method bodies AND any hand-written shadow that calls http* directly.`);
    lines.push(`   * No-op when \`permissions\` is undefined or no rule matches the path.`);
    lines.push(`   */`);
    lines.push(`  protected checkPathPermissions(verb: string, path: string): void {`);
    lines.push(`    if (!this.permissions) return;`);
    lines.push(`    const upperVerb = verb.toUpperCase();`);
    lines.push(`    for (const rule of PATH_PERMISSION_RULES) {`);
    lines.push(`      if (rule.verb !== upperVerb) continue;`);
    lines.push(`      if (!rule.pattern.test(path)) continue;`);
    lines.push(`      const missing = rule.perms.filter((p) => !this.permissions!.has(p));`);
    lines.push(`      if (missing.length > 0) {`);
    lines.push(
      `        throw new MissingPermissionError(rule.methodName, missing, [...this.permissions]);`,
    );
    lines.push(`      }`);
    lines.push(`      return;`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push('');
  }
  for (const method of methods) {
    const helper = verbToHelper[method.verb];
    if (!helper) continue;

    // Build the literal-string `paths[<path>][<verb>]` lookup keys.
    // openapi-typescript emits paths like `'/agent/list'` and verbs as
    // `'get' | 'post' | ...` keys. We use the *path with placeholders*
    // (e.g. `/agent/{agentId}`) - that's what openapi-typescript keys
    // by, not the runtime substituted form.
    const pathLiteral = JSON.stringify(method.pathTemplate.replace(/\$\{[^}]+\}/g, (_, n) => '{' + n + '}'));
    // Recover the original `{x}` form from the `${x}` template.
    // Actually pathTemplate started as `${x}` so we need to convert back.
    const specPathLiteral = JSON.stringify(
      method.pathTemplate.replace(/\$\{([^}]+)\}/g, '{$1}'),
    );
    const verbLiteral = JSON.stringify(method.verb);

    const reqType = method.bodyParam
      ? `RequestBodyOf<${specPathLiteral}, ${verbLiteral}>`
      : null;
    const respType = `ResponseOf<${specPathLiteral}, ${verbLiteral}>`;

    const args: string[] = [];
    for (const p of method.pathParams) args.push(`${p.name}: string`);
    if (reqType) args.push(`body: ${reqType}`);
    if (method.queryParam) args.push(`query?: Record<string, unknown>`);

    const callArgs = [`\`${method.pathTemplate}\``];
    if (method.verb === 'get') {
      if (method.queryParam) callArgs.push('query');
    } else if (method.verb === 'put') {
      if (reqType) callArgs.push('body');
      else callArgs.push('undefined');
      if (method.queryParam) callArgs.push('query');
    } else {
      if (reqType) callArgs.push('body');
    }

    lines.push(`  async ${method.name}(${args.join(', ')}): Promise<${respType}> {`);
    lines.push(`    return this.${helper}<${respType}>(${callArgs.join(', ')});`);
    lines.push(`  }`);
    lines.push('');
    // suppress unused var warnings
    void pathLiteral;
  }
  lines.push(`}`);
  return lines;
}

function newTsMorphProject(): Project {
  return new Project({
    useInMemoryFileSystem: false,
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      newLineKind: NewLineKind.LineFeed,
      quoteKind: QuoteKind.Single,
    },
  });
}

function resolveRepoRoot(context: EmitContext): string {
  // emitter-output-dir is configured per-emitter in tspconfig.yaml; we
  // ignore it and write directly into ts/<package>/src/generated/. The
  // tspconfig still has to set *something*, so we treat that path as
  // an anchor and walk back to the repo root.
  return resolvePath(context.emitterOutputDir, '..', '..', '..');
}

// ---------------------------------------------------------------------------
// Env package emit
// ---------------------------------------------------------------------------

function emitEnvPackage(program: Program, project: Project, repoRoot: string): void {
  const envNamespace = findNamespace(program, 'OpenboxEnv');
  if (!envNamespace) return;

  const envName = envNamespace.enums.get('EnvName');
  const envConfig = envNamespace.models.get('EnvConfig');
  const runtimeConfig = envNamespace.models.get('RuntimeConfig');
  const credentials = envNamespace.models.get('Credentials');
  const tokenEntry = envNamespace.models.get('TokenEntry');
  const tokenStoreModel = envNamespace.models.get('TokenStore');
  const envLoader = envNamespace.interfaces.get('EnvLoader');
  const tokenCodec = envNamespace.interfaces.get('TokenCodec');
  const clientNameResolver = envNamespace.interfaces.get('ClientNameResolver');
  const osPathResolver = envNamespace.interfaces.get('OsPathResolver');
  const clientVariantMarker = envNamespace.models.get('ClientVariant');
  const clientVariantPattern = clientVariantMarker?.properties.get('value')
    ? getTokenFormat(program, clientVariantMarker.properties.get('value')!)
    : undefined;

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts', 'env', 'src', 'generated', 'env-bindings.ts'),
    '',
    { overwrite: true },
  );

  // ts-morph's import-attribute API double-quotes the attribute value, so
  // skip it and write the import line as plain text.
  out.insertText(
    0,
    BANNER +
      '\n' +
      `import environmentsJson from '../../../../specs/environments.json' with { type: 'json' };\n\n`,
  );

  // EnvName + EnvConfig - generated from spec, imported (not redeclared)
  // by hand-written code in the same package.
  if (envName) {
    const members = [...envName.members.values()].map((m) => JSON.stringify(m.value ?? m.name));
    out.addStatements([`export type EnvName = ${members.join(' | ')};`, '']);
  }
  if (envConfig) {
    out.addStatements([emitInterface('EnvConfig', envConfig), '']);
  }
  out.addStatements([
    `export const ENVIRONMENTS: Record<EnvName, EnvConfig> = environmentsJson as Record<
  EnvName,
  EnvConfig
>;`,
    '',
  ]);

  // Generate the env-var binding table from @env_var decorators on
  // RuntimeConfig. Used by `resolveUrls()` so adding a new field on
  // the .tsp side automatically flows through.
  if (runtimeConfig) {
    const bindings = collectEnvVarBindings(program, runtimeConfig);
    if (bindings.length > 0) {
      out.addStatements([
        `export const ENV_VAR_BINDINGS = {`,
        ...bindings.map(
          (b) => `  ${quoteIdent(b.field)}: ${JSON.stringify(b.envVar)} as const,`,
        ),
        `} as const;`,
        '',
      ]);
    }
  }

  // Generate the API-key validator from @token_format on Credentials.
  if (credentials) {
    const apiKey = credentials.properties.get('apiKey');
    const pattern = apiKey ? getTokenFormat(program, apiKey) : undefined;
    if (pattern) {
      out.addStatements([
        `const API_KEY_PATTERN = ${tsRegexLiteral(pattern)};`,
        '',
        `export function validateApiKeyFormat(value: string): true | string {
  if (!API_KEY_PATTERN.test(value)) {
    return 'OPENBOX_API_KEY must match obx_(live|test)_<48hex>';
  }
  return true;
}`,
        '',
      ]);
    }
  }

  // Generate an OS-path resolver hint table for fields tagged @os_path.
  if (credentials) {
    const osPathFields: string[] = [];
    for (const [name, prop] of credentials.properties) {
      if (isOsPath(program, prop)) osPathFields.push(name);
    }
    if (osPathFields.length > 0) {
      out.addStatements([
        `export const OS_PATH_FIELDS = ${JSON.stringify(osPathFields)} as const;`,
        '',
      ]);
    }
  }

  // Persisted-tokens shape (TokenEntry + TokenStore) - codec wire
  // format every language must agree on.
  if (tokenEntry) {
    out.addStatements([emitInterface('TokenEntry', tokenEntry), '']);
  }
  if (tokenStoreModel) {
    out.addStatements([emitInterface('TokenStore', tokenStoreModel), '']);
  }

  // FeatureMap is the "convenience alias for Record<string, boolean>"
  // that the hand-written code imports today; we keep it as a generated
  // alias instead of redeclaring on the impl side.
  out.addStatements([
    `export type FeatureMap = NonNullable<TokenEntry['features']>;`,
    '',
  ]);

  // Construction-time config models - `BackendClientConfig` /
  // `CoreClientConfig` / `RetryConfig` / `RateLimitConfig` /
  // `TokenPair` / `ApiError`. Emit anything we haven't already
  // hand-picked above so adding a new option model in the spec
  // flows through without an emitter edit.
  const alreadyEmitted = new Set([
    'EnvConfig',
    'RuntimeConfig',
    'Credentials',
    'TokenEntry',
    'TokenStore',
    'ClientVariant',
    'Runtime',
  ]);
  for (const [modelName, model] of envNamespace.models) {
    if (alreadyEmitted.has(modelName)) continue;
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }

  // EnvLoader / TokenCodec / ClientNameResolver - runtime contracts
  // that hand-written code must implement. Drift between spec and
  // impl fails `tsc --noEmit`.
  if (envLoader) {
    out.addStatements([emitInterfaceFromOps('EnvLoader', envLoader), '']);
  }
  if (tokenCodec) {
    out.addStatements([emitInterfaceFromOps('TokenCodec', tokenCodec), '']);
  }
  if (clientNameResolver) {
    out.addStatements([emitInterfaceFromOps('ClientNameResolver', clientNameResolver), '']);
  }
  if (osPathResolver) {
    out.addStatements([emitInterfaceFromOps('OsPathResolver', osPathResolver), '']);
  }

  // OsPathScope enum - drives the per-OS path lookup. Emit the
  // string-literal union form so callers can `import type { OsPathScope }`
  // and write `resolveOsPath('tokens')`.
  const osPathScopeEnum = envNamespace.enums.get('OsPathScope');
  if (osPathScopeEnum) {
    const members = [...osPathScopeEnum.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type OsPathScope = ${members.join(' | ')};`, '']);
  }
  if (clientVariantPattern) {
    out.addStatements([
      `export const CLIENT_VARIANT_PATTERN = ${tsRegexLiteral(clientVariantPattern)};`,
      '',
    ]);
  }
}

// ---------------------------------------------------------------------------
// CLI package emit
// ---------------------------------------------------------------------------

interface FlagEntry {
  name: string;
  long: string;
  short: string | undefined;
  description: string;
  env: string | undefined;
  optional: boolean;
  tsType: string;
}

interface SubcommandEntry {
  name: string;
  flags: FlagEntry[];
}

interface ManifestEntry {
  command: string;
  description: string | undefined;
  interfaceName: string;
  subcommands: SubcommandEntry[];
}

function emitCliPackage(program: Program, project: Project, repoRoot: string): void {
  const cliNamespace = findNamespace(program, 'OpenboxCli');
  if (!cliNamespace) return;

  // Skip emit if no @cli_command interfaces present.
  const commands: { name: string; iface: Interface }[] = [];
  for (const [name, iface] of cliNamespace.interfaces) {
    if (getCommand(program, iface)) commands.push({ name, iface });
  }
  if (commands.length === 0) return;

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts', 'cli', 'src', 'generated', 'cli-bindings.ts'),
    '',
    { overwrite: true },
  );

  out.insertText(0, BANNER + '\n\n');

  // Emit every enum + model referenced by the interfaces, so the emitted
  // file is self-contained - no `import type { EnvFlag } from '../../...'`
  // dance for hand-written code.
  for (const [enumName, enumType] of cliNamespace.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of cliNamespace.models) {
    out.addStatements([emitInterface(modelName, model), '']);
  }

  const manifest: ManifestEntry[] = [];

  for (const { name, iface } of commands) {
    const cmd = getCommand(program, iface)!;

    out.addStatements([emitInterfaceFromOps(name, iface), '']);

    const subcommands: SubcommandEntry[] = [];
    for (const [opName, op] of iface.operations) {
      const flags: FlagEntry[] = [];
      for (const [pname, p] of op.parameters.properties) {
        const fb = getFlag(program, p);
        if (!fb) continue;
        flags.push({
          name: pname,
          long: kebabCaseLocal(pname),
          short: fb.short,
          description: fb.description,
          env: fb.env,
          optional: p.optional,
          tsType: tspTypeToTs(p.type),
        });
      }
      subcommands.push({ name: opName, flags });
    }

    manifest.push({
      command: cmd.name,
      description: cmd.description,
      interfaceName: name,
      subcommands,
    });
  }

  out.addStatements([
    '/**',
    ' * Canonical CLI surface - every command-tree node declared in',
    ' * specs/typespec/cli/. The hand-written commander registration in',
    ' * ts/cli/src/main.ts walks this manifest so a spec edit (rename a',
    ' * flag, add a subcommand) propagates without a code edit.',
    ' */',
    `export const CLI_COMMAND_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;`,
    '',
    'export type CliCommandManifest = typeof CLI_COMMAND_MANIFEST;',
    '',
  ]);
}

function kebabCaseLocal(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

// ---------------------------------------------------------------------------
// HTTP endpoint manifest emit (ts/client + ts/core-client)
// ---------------------------------------------------------------------------
//
// Walks an HTTP-service namespace via @typespec/http's listHttpOperationsIn
// and emits a `<NAME>_ENDPOINT_MANIFEST` array of every (path, verb,
// operationId) tuple. Tests in tests/unit/endpoint-coverage.test.ts read
// the manifest and assert each entry has a matching method on the
// hand-written wrapper class - adding a route to the spec without a
// matching wrapper method now fails CI.

interface EndpointEntry {
  operationId: string;
  path: string;
  verb: string;
  // The path normalized so {placeholders} become a regex-safe form for
  // grep-matching against fetch URLs in hand-written code.
  pathPattern: string;
}

function emitEndpointManifest(
  program: Program,
  project: Project,
  repoRoot: string,
  namespaceName: string,
  exportName: string,
  outRel: string,
): void {
  const ns = findNamespace(program, namespaceName);
  if (!ns) return;

  const [ops] = listHttpOperationsIn(program, ns);
  const entries: EndpointEntry[] = ops.map((o) => ({
    operationId: o.operation.name,
    path: o.path,
    verb: o.verb,
    pathPattern: o.path.replace(/\{[^}]+\}/g, '{x}'),
  }));

  if (entries.length === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  out.addStatements([
    `/**`,
    ` * Every HTTP operation declared on the ${namespaceName} TypeSpec`,
    ` * namespace. Tests in tests/unit/endpoint-coverage.test.ts walk this`,
    ` * array and assert the hand-written wrapper class has a method`,
    ` * implementing each entry - adding a path here without a wrapper`,
    ` * method fails CI.`,
    ` */`,
    `export const ${exportName} = ${JSON.stringify(entries, null, 2)} as const;`,
    '',
    `export type ${pascal(exportName)}Entry = (typeof ${exportName})[number];`,
    '',
  ]);
}

function pascal(s: string): string {
  return s
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

// ---------------------------------------------------------------------------
// Namespace-types emit - drops every enum/model/scalar declared on a
// service namespace into a single TS file. Used to give per-package
// wrappers (ts/core-client, ts/client govern) a single import path
// for their wire types instead of redeclaring each one inline.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Govern-protocol emit - walks every @preset interface in OpenboxGovern
// and emits one Session class per preset, plus a base class that owns
// the lifecycle invariants (terminal events guaranteed via try/finally
// + process-exit handlers, idempotent close, paired Start/Complete).
// User code never touches Workflow{Started,Completed,Failed} - those
// are SDK-internal, fired by the runtime.
// ---------------------------------------------------------------------------

interface PresetMethod {
  /** Method name on the preset interface (camelCase). */
  name: string;
  /** Canonical event_type to stamp on the wire. Undefined only on the
   *  special `custom` preset whose `activity()` takes it as a parameter. */
  eventType?: CanonicalEventType;
  /** Free-form activity_type. Undefined → falls back to method name. */
  activityType?: string;
}

interface PresetEntry {
  /** Lowercase-hyphen identifier from @preset(name) - wire-stable. */
  name: string;
  /** PascalCase preset class prefix: ClaudeCode, LangChain, Default, Custom. */
  pascal: string;
  /** camelCase registry key: claudeCode, langChain, default, custom. */
  camel: string;
  /** Original TS interface name from the spec (e.g. "ClaudeCodePreset"). */
  ifaceName: string;
  /** Methods declared on the preset interface. */
  methods: PresetMethod[];
  /** True for the special `custom` preset. */
  isCustom: boolean;
}

function emitGovernProtocol(program: Program, project: Project, repoRoot: string): void {
  const ns = findNamespace(program, 'OpenboxGovern');
  if (!ns) return;

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts/core-client/src/generated/govern.ts'),
    '',
    { overwrite: true },
  );
  out.insertText(0, BANNER + '\n\n');

  // Tier 1 - emit every enum + model in the namespace (CanonicalEventType,
  // ActivityStage, VerdictArm, WorkflowVerdict, GovernedPayload). These
  // are the locked envelope plus the public verdict + payload shapes.
  for (const [enumName, enumType] of ns.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of ns.models) {
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }

  // Mark the verdict model so downstream code can branch off it.
  let verdictModelName = 'WorkflowVerdict';
  for (const [modelName, model] of ns.models) {
    if (isVerdict(program, model)) {
      verdictModelName = modelName;
      out.addStatements([`export type CanonicalVerdict = ${modelName};`, '']);
      break;
    }
  }

  // Tier 2 - walk every @preset interface, collect methods + envelope
  // mappings. The `custom` preset is special: its `activity` operation
  // takes (activityType, stage, payload) and routes via the runtime,
  // so we don't bake a fixed envelope into the method.
  const presets: PresetEntry[] = [];
  for (const [ifaceName, iface] of ns.interfaces) {
    const preset = getPreset(program, iface);
    if (!preset) continue;

    const isCustom = preset.name === 'custom';
    const methods: PresetMethod[] = [];
    for (const [opName, op] of iface.operations) {
      if (isCustom) {
        methods.push({ name: opName });
        continue;
      }
      const m = getMapsTo(program, op);
      if (!m) continue;
      methods.push({
        name: opName,
        eventType: m.eventType,
        activityType: m.activityType ?? opName,
      });
    }
    if (methods.length === 0) continue;
    presets.push({
      name: preset.name,
      pascal: pascal(preset.name.replace(/-/g, '_')),
      camel: kebabToCamel(preset.name),
      ifaceName,
      methods,
      isCustom,
    });
  }

  if (presets.length === 0) return;

  // Stable sort for deterministic output.
  presets.sort((a, b) => a.name.localeCompare(b.name));

  // Emit the manifest (one JSON-friendly entry per preset method) so
  // tests and downstream tooling can introspect what shipped.
  const manifest = presets.map((p) => ({
    preset: p.name,
    methods: p.methods.map((m) => ({
      name: m.name,
      eventType: m.eventType,
      activityType: m.activityType,
    })),
  }));
  out.addStatements([
    '/** Spec-driven manifest of every preset + its method envelopes. */',
    `export const PRESET_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;`,
    '',
    'export type PresetName = (typeof PRESET_MANIFEST)[number]["preset"];',
    '',
  ]);

  out.addStatements([emitBaseSession(verdictModelName), '']);
  for (const p of presets) {
    out.addStatements([emitPresetSession(p, verdictModelName), '']);
  }
  out.addStatements([emitPresetsRegistry(presets), '']);
  out.addStatements([emitGovernHelper(verdictModelName), '']);
  out.addStatements([emitVerdictHelpers(verdictModelName), '']);
}

function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Adapter emit (Stage 1.4)
//
// Walks the OpenboxGovern.Adapters namespace, finds every interface
// carrying @adapter, and materializes one runtime/<name>.ts module per
// adapter. The module exports a `createXxxAdapter()` factory that:
//   1. Reads stdin JSON.
//   2. Dispatches by the adapter's discriminator field to the matching
//      @hookEvent operation's user-supplied handler.
//   3. Translates the WorkflowVerdict the handler returns to stdout
//      JSON via a fixed @verdictShape registry.
//   4. Writes stdout + exits 0.
//
// User code provides the handler bodies (typically calling a preset
// Session method); the spec-driven adapter handles all transport boilerplate.
// ---------------------------------------------------------------------------

interface AdapterMethod {
  name: string;
  eventName: string;
  shape: VerdictShape;
}

interface AdapterEntry {
  /** Adapter name (`claude-hooks`, `cursor-hooks`). */
  name: string;
  /** Bound preset name (`claude-code`, `cursor`). */
  preset: string;
  /** Stdin JSON field used to discriminate operations. */
  discriminator: string;
  /** Generated factory class name (`ClaudeHooks` → `createClaudeHooksAdapter`). */
  pascal: string;
  /** Envelope model name from the operations' parameter type. */
  envelopeName: string;
  methods: AdapterMethod[];
}

function emitAdapters(program: Program, project: Project, repoRoot: string): void {
  const ns = findNamespace(program, 'OpenboxGovern.Adapters');
  if (!ns) return;

  const adapters: AdapterEntry[] = [];
  for (const [ifaceName, iface] of ns.interfaces) {
    const binding = getAdapter(program, iface);
    if (!binding) continue;

    let envelopeName: string | undefined;
    const methods: AdapterMethod[] = [];
    for (const [opName, op] of iface.operations) {
      const ev = getHookEvent(program, op);
      if (!ev) continue;
      const vs = getVerdictShape(program, op);
      if (!vs) continue;
      const param = op.parameters?.properties?.values().next().value;
      if (param?.type?.kind === 'Model') {
        envelopeName ??= param.type.name;
      }
      methods.push({
        name: opName,
        eventName: ev.eventName,
        shape: vs.shape,
      });
    }
    if (methods.length === 0) continue;
    adapters.push({
      name: binding.name,
      preset: binding.preset,
      discriminator: binding.discriminator,
      pascal: pascal(binding.name.replace(/-/g, '_')),
      envelopeName: envelopeName ?? 'unknown',
      methods,
    });
  }
  if (adapters.length === 0) return;

  // Stable order - file ordering needs to be deterministic.
  adapters.sort((a, b) => a.name.localeCompare(b.name));

  // Emit envelope models from the Adapters namespace into a shared types
  // file, plus one runtime/<name>.ts per adapter that imports them.
  const sharedTypes = project.createSourceFile(
    resolvePath(repoRoot, 'ts/core-client/src/generated/runtime/envelopes.ts'),
    '',
    { overwrite: true },
  );
  sharedTypes.insertText(0, BANNER + '\n\n');
  for (const [modelName, model] of ns.models) {
    if (modelName === 'Array' || modelName === 'Record') continue;
    sharedTypes.addStatements([emitInterface(modelName, model), '']);
  }

  for (const a of adapters) {
    const out = project.createSourceFile(
      resolvePath(repoRoot, `ts/core-client/src/generated/runtime/${a.name}.ts`),
      '',
      { overwrite: true },
    );
    out.insertText(0, BANNER + '\n\n');
    out.addStatements([emitAdapterModule(a), '']);
  }

  // Index re-export so consumers can import via `runtime/<name>`.
  const index = project.createSourceFile(
    resolvePath(repoRoot, 'ts/core-client/src/generated/runtime/index.ts'),
    '',
    { overwrite: true },
  );
  index.insertText(0, BANNER + '\n\n');
  index.addStatements([
    `export * from './envelopes.js';`,
    ...adapters.map((a) => `export * from './${a.name}.js';`),
    '',
  ]);
}

function emitAdapterModule(a: AdapterEntry): string {
  const factoryName = `create${a.pascal}Adapter`;
  const handlersIface = `${a.pascal}AdapterHandlers`;
  const configIface = `${a.pascal}AdapterConfig`;
  const presetCamel = kebabToCamel(a.preset);
  const presetSessionTy = `${pascal(a.preset.replace(/-/g, '_'))}Session`;

  const handlerSigs = a.methods
    .map(
      (m) =>
        `  ${m.name}?: (input: ${a.envelopeName}, session: ${presetSessionTy}) => Promise<WorkflowVerdict | undefined | void>;`,
    )
    .join('\n');

  const dispatchCases = a.methods
    .map(
      (m) =>
        `    case ${JSON.stringify(m.eventName)}: {
      if (!handlers.${m.name}) {
        writeFallback(${JSON.stringify(m.shape)}, undefined, env);
        return;
      }
      const verdict = await handlers.${m.name}(env, session);
      writeVerdict(${JSON.stringify(m.shape)}, verdict, env);
      return;
    }`,
    )
    .join('\n');

  return `import type { OpenBoxCoreClient } from '../../core-client.js';
import { govern, presets, type ${presetSessionTy}, type WorkflowVerdict } from '../govern.js';
import type { ${a.envelopeName} } from './envelopes.js';

export type { ${a.envelopeName} };

/**
 * Per-event handlers. Each handler receives the parsed stdin envelope
 * + an attached ${presetSessionTy} (workflowId/runId resolved by
 * \`config.resolveSession\`). Return a WorkflowVerdict - usually by calling
 * a preset method like \`session.preToolUse(...)\`. The adapter writes
 * the verdict-mapped stdout JSON automatically per the operation's
 * @verdictShape. Returning undefined writes the default \`allow\` shape.
 */
export interface ${handlersIface} {
${handlerSigs}
}

export interface ${configIface} {
  /** Authenticated core client (agent-scoped API key). */
  core: OpenBoxCoreClient;
  /** Per-stdin-message resolver - typically reads sessionStore.json. */
  resolveSession: (
    env: ${a.envelopeName},
  ) => Promise<{ workflowId: string; runId: string }>;
  handlers: ${handlersIface};
  /** Override stdin source (test injection). Default: process.stdin. */
  readStdin?: () => Promise<string>;
  /** Override stdout sink (test injection). Default: process.stdout.write. */
  writeStdout?: (data: string) => void;
  /** Override exit (test injection). Default: process.exit. */
  exit?: (code: number) => never;
}

/**
 * Build the ${a.name} runtime adapter. Call \`.run()\` from the hook
 * binary's main(). Generated from specs/typespec/govern/adapters.tsp.
 */
export function ${factoryName}(config: ${configIface}) {
  const readStdin = config.readStdin ?? defaultReadStdin;
  const write = config.writeStdout ?? ((data: string) => process.stdout.write(data));
  const exit = config.exit ?? ((code: number) => process.exit(code));

  function writeFallback(shape: string, _v: WorkflowVerdict | undefined | void, env: ${a.envelopeName}): void {
    const json = renderVerdictOutput(shape as Shape, undefined, env);
    if (json !== undefined) write(JSON.stringify(json));
  }
  function writeVerdict(shape: string, v: WorkflowVerdict | undefined | void, env: ${a.envelopeName}): void {
    const json = renderVerdictOutput(shape as Shape, v ?? undefined, env);
    if (json !== undefined) write(JSON.stringify(json));
  }

  return {
    async run(): Promise<void> {
      const raw = (await readStdin()).trim();
      if (!raw) return exit(0);
      let env: ${a.envelopeName};
      try {
        env = JSON.parse(raw) as ${a.envelopeName};
      } catch {
        return exit(0);
      }
      const eventName = (env as unknown as Record<string, unknown>)[${JSON.stringify(a.discriminator)}];
      if (typeof eventName !== 'string' || !eventName) return exit(0);

      const { workflowId, runId } = await config.resolveSession(env);
      const session = govern.attach({
        core: config.core,
        preset: presets.${presetCamel},
        workflowId,
        runId,
      });

      const handlers = config.handlers;
      try {
        await dispatch(eventName, env, session, handlers, writeFallback, writeVerdict);
      } finally {
        return exit(0);
      }
    },
  };
}

async function dispatch(
  eventName: string,
  env: ${a.envelopeName},
  session: ${presetSessionTy},
  handlers: ${handlersIface},
  writeFallback: (shape: string, v: WorkflowVerdict | undefined | void, env: ${a.envelopeName}) => void,
  writeVerdict: (shape: string, v: WorkflowVerdict | undefined | void, env: ${a.envelopeName}) => void,
): Promise<void> {
  switch (eventName) {
${dispatchCases}
    default:
      return;
  }
}

async function defaultReadStdin(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk as Buffer);
  }
  return Buffer.concat(chunks).toString('utf-8');
}

${VERDICT_SHAPE_REGISTRY_SOURCE}
`;
}

const VERDICT_SHAPE_REGISTRY_SOURCE = `// ─── Verdict-shape registry ─────────────────────────────────────────────
// Translates a WorkflowVerdict to stdout JSON per the operation's
// @verdictShape. Adding a new shape requires extending the union below
// AND updating the typespec-workflow VerdictShape union.

type Shape =
  | 'permission-decision'
  | 'decision-block'
  | 'permission-request'
  | 'cursor-permission'
  | 'cursor-observe'
  | 'none';

function renderVerdictOutput(
  shape: Shape,
  v: WorkflowVerdict | undefined,
  env: { hook_event_name?: string },
): unknown {
  const arm = v?.arm ?? 'allow';
  const reason = v?.reason ?? '';
  switch (shape) {
    case 'permission-decision': {
      if (arm === 'allow' || arm === 'constrain') {
        return { hookSpecificOutput: { permissionDecision: 'allow' } };
      }
      if (arm === 'require_approval') {
        return {
          hookSpecificOutput: {
            permissionDecision: 'ask',
            permissionDecisionReason: reason || 'OpenBox: approval required',
          },
        };
      }
      // block / halt
      return {
        hookSpecificOutput: {
          permissionDecision: 'deny',
          permissionDecisionReason: reason || 'OpenBox: blocked by policy',
        },
      };
    }
    case 'decision-block': {
      if (arm === 'block' || arm === 'halt') {
        return {
          decision: 'block',
          reason: reason || 'OpenBox: blocked by policy',
        };
      }
      return {};
    }
    case 'permission-request': {
      const eventName = env.hook_event_name ?? 'PermissionRequest';
      if (arm === 'allow' || arm === 'constrain') {
        return {
          hookSpecificOutput: {
            hookEventName: eventName,
            decision: { behavior: 'allow' },
          },
        };
      }
      return {
        hookSpecificOutput: {
          hookEventName: eventName,
          decision: {
            behavior: 'deny',
            message: reason || 'OpenBox: blocked by policy',
          },
        },
      };
    }
    case 'cursor-permission': {
      if (arm === 'allow' || arm === 'constrain') return { permission: 'allow' };
      if (arm === 'require_approval') {
        return {
          permission: 'deny',
          userMessage: reason || 'OpenBox: approval required',
          agentMessage: 'OpenBox: awaiting human approval',
        };
      }
      if (arm === 'halt') {
        return {
          permission: 'deny',
          userMessage: 'OpenBox HALT: ' + (reason || 'session halted'),
          agentMessage: 'OpenBox HALT: do not proceed',
        };
      }
      return {
        permission: 'deny',
        userMessage: reason || 'OpenBox: blocked by policy',
      };
    }
    case 'cursor-observe':
      return {};
    case 'none':
      return undefined;
  }
}
`;

function emitBaseSession(verdictModelName: string): string {
  return `import { randomUUID } from 'crypto';
import type { OpenBoxCoreClient } from '../core-client.js';
import type {
  GovernanceEventPayload,
  GovernanceVerdictResponse,
} from './core-types.js';

/**
 * Construction options for any preset Session class. The \`core\` client
 * is the authenticated transport; the other fields define this workflow
 * run's identity. The runtime owns the lifecycle - Workflow{Started,
 * Completed,Failed} fire automatically on \`govern()\` enter/exit/throw,
 * and via process-exit handlers if the session is still open at exit.
 */
export interface GovernedSessionConfig {
  core: OpenBoxCoreClient;
  /** Stable identifier for this workflow run. */
  workflowId?: string;
  /** Per-attempt run identifier. */
  runId?: string;
  /** Workflow-class identifier surfaced to observability. */
  workflowType?: string;
  /** Originating runtime tag (\`langgraph\` / \`temporal\` / \`mastra\` / ...). */
  taskQueue?: string;
  /**
   * Initial polling interval (ms) when the verdict is \`require_approval\`.
   * The runtime exponentially backs this off (× factor) up to a cap on
   * each attempt so a fast decision doesn't waste a long sleep, but a
   * slow decision doesn't pound core. Default: 500ms.
   */
  approvalPollIntervalMs?: number;
  /**
   * Cap (ms) on the per-attempt poll interval after backoff. Default: 5000ms.
   * The actual sleep is also bounded by min(approvalMaxWaitMs, approvalExpiresAt)
   * so we never overshoot the deadline.
   */
  approvalPollMaxIntervalMs?: number;
  /**
   * Multiplier applied to the poll interval after each attempt. 1.0 = no
   * backoff (fixed interval). Default: 1.5 (gentle exponential).
   */
  approvalPollBackoffFactor?: number;
  /**
   * Random jitter applied to each poll interval as a fraction of the
   * computed interval. 0.25 means ±25%. Default: 0.25. Avoids
   * thundering-herd when a fleet of agents wait on the same approval.
   */
  approvalPollJitter?: number;
  /** Maximum total wait (ms) for an approval decision. Default: 60_000ms. */
  approvalMaxWaitMs?: number;
  /**
   * If true, register process-exit handlers (SIGINT/SIGTERM/uncaughtException
   * /unhandledRejection/beforeExit) that fire \`WorkflowFailed\` best-effort
   * before the process dies. Default: true. Set false for short-lived
   * scripts where the cleanup is wasteful.
   */
  registerExitHandlers?: boolean;
  /**
   * Internal flag set by \`govern.attach()\`. When true, the session starts
   * in the \`opened\` state - \`runActivity\` will NOT auto-fire WorkflowStarted,
   * and explicit \`workflowStarted()\` calls become no-ops (idempotent).
   * The parent process is assumed to have already fired the workflow open
   * event. Don't set this manually - use \`govern.attach()\`.
   */
  attached?: boolean;
}

/**
 * Thrown when a session method is called after the session has been
 * terminated (workflowCompleted/Failed already fired). Tries to call
 * activity()/preset methods after this point would silently emit
 * orphan events without the SDK invariant - we throw instead.
 */
export class SessionAlreadyTerminatedError extends Error {
  constructor() {
    super('[govern] session already terminated; create a new govern() scope to continue.');
    this.name = 'SessionAlreadyTerminatedError';
  }
}

/**
 * Lifecycle-owning base class. Every preset Session class extends this
 * and delegates its public methods to \`runActivity()\`. User code never
 * calls \`begin()\` / \`complete()\` / \`fail()\` directly - the \`govern()\`
 * helper drives them via try/finally.
 */
export class BaseGovernedSession {
  readonly workflowId: string;
  readonly runId: string;
  readonly workflowType: string;
  readonly taskQueue: string;

  protected readonly core: OpenBoxCoreClient;
  private readonly approvalPollIntervalMs: number;
  private readonly approvalPollMaxIntervalMs: number;
  private readonly approvalPollBackoffFactor: number;
  private readonly approvalPollJitter: number;
  private readonly approvalMaxWaitMs: number;
  private opened = false;
  private finalized = false;
  private readonly autoOpenSuppressed: boolean;
  private readonly inFlight = new Set<string>();
  private readonly exitHandlerCleanup: Array<() => void> = [];

  constructor(config: GovernedSessionConfig) {
    this.core = config.core;
    this.workflowId = config.workflowId ?? randomUUID();
    this.runId = config.runId ?? randomUUID();
    this.workflowType = config.workflowType ?? 'governed_agent';
    this.taskQueue = config.taskQueue ?? 'generic';
    this.approvalPollIntervalMs = config.approvalPollIntervalMs ?? 500;
    this.approvalPollMaxIntervalMs = config.approvalPollMaxIntervalMs ?? 5_000;
    this.approvalPollBackoffFactor = config.approvalPollBackoffFactor ?? 1.5;
    this.approvalPollJitter = config.approvalPollJitter ?? 0.25;
    this.approvalMaxWaitMs = config.approvalMaxWaitMs ?? 60_000;
    this.autoOpenSuppressed = config.attached === true;
    if (config.registerExitHandlers !== false) {
      this.installExitHandlers();
    }
  }

  /** True once \`begin()\` has been called. */
  get isOpen(): boolean {
    return this.opened && !this.finalized;
  }

  /** True after a terminal event (Workflow{Completed,Failed}) fired. */
  get isTerminated(): boolean {
    return this.finalized;
  }

  /**
   * Fire WorkflowStarted. Idempotent - safe to call multiple times,
   * only the first emits. Public so harness-owned consumers (claude-hooks,
   * cursor-hooks) can drive lifecycle when the workflow spans processes.
   * \`govern()\` calls this automatically before the body runs;
   * \`govern.attach()\` does NOT - caller decides when (if ever).
   *
   * Backward-compat alias: \`begin()\`.
   */
  async workflowStarted(): Promise<void> {
    if (this.opened) return;
    this.opened = true;
    await this.emit({ event_type: 'WorkflowStarted' });
  }
  /** @deprecated use \`workflowStarted()\` - same behavior. */
  async begin(): Promise<void> {
    return this.workflowStarted();
  }

  /**
   * Fire WorkflowCompleted. Idempotent. Same public/cross-process
   * rationale as \`workflowStarted\`. \`govern()\` calls this on the
   * happy-path return from the body; \`govern.attach()\` does NOT.
   *
   * Backward-compat alias: \`complete()\`.
   */
  async workflowCompleted(): Promise<void> {
    if (this.finalized) return;
    this.finalized = true;
    await this.emit({ event_type: 'WorkflowCompleted', status: 'completed' });
    this.cleanupExitHandlers();
  }
  /** @deprecated use \`workflowCompleted()\` - same behavior. */
  async complete(): Promise<void> {
    return this.workflowCompleted();
  }

  /**
   * Fire WorkflowFailed with an error payload. Idempotent. \`govern()\`
   * calls this if the body throws or if a process-exit handler fires;
   * \`govern.attach()\` does NOT - caller invokes explicitly on harness-
   * signaled session failure.
   *
   * Backward-compat alias: \`fail()\`.
   */
  async workflowFailed(error?: unknown): Promise<void> {
    if (this.finalized) return;
    this.finalized = true;
    await this.emit({
      event_type: 'WorkflowFailed',
      status: 'failed',
      error: errorInfoFrom(error),
    });
    this.cleanupExitHandlers();
  }
  /** @deprecated use \`workflowFailed()\` - same behavior. */
  async fail(error?: unknown): Promise<void> {
    return this.workflowFailed(error);
  }

  /**
   * Run one activity through the canonical envelope. Preset classes
   * call this with their fixed (eventType, activityType) tuple; the
   * \`custom\` preset takes them from the user.
   *
   * Strategy depends on \`eventType\`:
   *   ActivityStarted   → emit start; pre-stage block → no completion fired.
   *                       Otherwise emit a paired ActivityCompleted.
   *   ActivityCompleted → emit completion only (post-stage observe / gate).
   *   SignalReceived    → fire-and-forget telemetry (no gate).
   */
  protected async runActivity(
    eventType: 'ActivityStarted' | 'ActivityCompleted' | 'SignalReceived',
    activityType: string,
    payload: GovernedPayload,
  ): Promise<${verdictModelName}> {
    if (this.finalized) throw new SessionAlreadyTerminatedError();
    if (!this.opened && !this.autoOpenSuppressed) await this.begin();
    const activityId = randomUUID();
    this.inFlight.add(activityId);

    try {
      if (eventType === 'SignalReceived') {
        return this.emit({
          event_type: 'SignalReceived',
          activity_id: activityId,
          activity_type: activityType,
          activity_input: payload.input,
        });
      }

      if (eventType === 'ActivityStarted') {
        const startedVerdict = await this.emit({
          event_type: 'ActivityStarted',
          activity_id: activityId,
          activity_type: activityType,
          activity_input: payload.input,
        });
        if (startedVerdict.arm !== 'allow') {
          // Pre-stage block - never emit ActivityCompleted, but if the
          // gate said require_approval, poll for the approval decision.
          if (
            startedVerdict.arm === 'require_approval' &&
            startedVerdict.approvalId
          ) {
            return this.pollApproval(activityId, startedVerdict);
          }
          return startedVerdict;
        }
        // Allow → emit the matching ActivityCompleted with the payload's
        // output (or undefined if the user only has input at start time).
        return this.emitCompleted(activityId, activityType, payload);
      }

      // eventType === 'ActivityCompleted' - post-stage gate.
      return this.emitCompleted(activityId, activityType, payload);
    } finally {
      this.inFlight.delete(activityId);
    }
  }

  private async emitCompleted(
    activityId: string,
    activityType: string,
    payload: GovernedPayload,
  ): Promise<${verdictModelName}> {
    const completedVerdict = await this.emit({
      event_type: 'ActivityCompleted',
      activity_id: activityId,
      activity_type: activityType,
      activity_input: payload.input,
      activity_output: payload.output,
    });
    if (
      completedVerdict.arm === 'require_approval' &&
      completedVerdict.approvalId
    ) {
      return this.pollApproval(activityId, completedVerdict);
    }
    return completedVerdict;
  }

  private async emit(
    event: Pick<
      GovernanceEventPayload,
      'event_type' | 'activity_id' | 'activity_type' | 'activity_input' | 'activity_output' | 'status' | 'error'
    >,
  ): Promise<${verdictModelName}> {
    const payload = {
      ...event,
      source: 'workflow-telemetry',
      workflow_id: this.workflowId,
      run_id: this.runId,
      workflow_type: this.workflowType,
      task_queue: this.taskQueue,
      timestamp: new Date().toISOString(),
    } as unknown as GovernanceEventPayload;
    const response = await this.core.evaluate(payload);
    return mapVerdict(response);
  }

  private async pollApproval(
    activityId: string,
    initial: ${verdictModelName},
  ): Promise<${verdictModelName}> {
    // ── Polling design notes ──
    // Bounded by both config max-wait AND the server-supplied
    // approvalExpiresAt (whichever is sooner) so we never overshoot.
    // Exponential backoff (× factor each attempt, capped at maxIntervalMs)
    // matches the bimodal latency of approvals (decided in seconds OR
    // minutes) without burning a long sleep when the answer's right there.
    // ±jitter randomizes per-attempt delay so a fleet of agents waiting
    // on the same approval window doesn't thunder-herd core in lockstep.
    //
    // Future: backend WS gateway already broadcasts APPROVAL_DECIDED to
    // org rooms (\`openbox-backend\` ws-events.gateway.ts:353), but its
    // auth path requires a Keycloak JWT and the SDK runtime carries an
    // \`obx_live_*\` API key - wire-incompatible. Replacing this poll
    // loop with a WS subscription requires API-key auth to land on the
    // \`/ws\` namespace upstream first.
    const cfgDeadline = Date.now() + this.approvalMaxWaitMs;
    const srvDeadline = initial.approvalExpiresAt
      ? new Date(initial.approvalExpiresAt).getTime()
      : Number.POSITIVE_INFINITY;
    const deadline = Math.min(cfgDeadline, srvDeadline);

    let nextInterval = this.approvalPollIntervalMs;
    while (Date.now() < deadline) {
      const remaining = deadline - Date.now();
      const jittered = applyJitter(nextInterval, this.approvalPollJitter);
      // Never sleep past the deadline.
      await sleep(Math.max(0, Math.min(jittered, remaining)));
      const status = await this.core.pollApproval({
        workflow_id: this.workflowId,
        run_id: this.runId,
        activity_id: activityId,
      });
      if (status.action && status.action !== 'require_approval') {
        return {
          arm: normalizeArm(status.action),
          approvalId: initial.approvalId,
          approvalExpiresAt: status.approval_expiration_time,
          reason: status.reason,
          riskScore: initial.riskScore,
          trustTier: initial.trustTier,
        };
      }
      nextInterval = Math.min(
        nextInterval * this.approvalPollBackoffFactor,
        this.approvalPollMaxIntervalMs,
      );
    }
    return initial;
  }

  /**
   * Best-effort handlers for process death. SIGINT/SIGTERM/uncaught
   * exceptions get a brief async window to fire WorkflowFailed; \`exit\`
   * is synchronous-only so we just log a warning. Multiple sessions in
   * the same process each register their own handlers; cleanup on
   * normal completion removes them.
   */
  private installExitHandlers(): void {
    if (typeof process === 'undefined' || !process.on) return;

    const failOnSignal = (reason: string) => async () => {
      if (this.finalized) return;
      try {
        await Promise.race([
          this.fail(new Error(\`process_exit:\${reason}\`)),
          sleep(2_000),
        ]);
      } catch {
        // best-effort
      }
    };

    const sigint = failOnSignal('SIGINT');
    const sigterm = failOnSignal('SIGTERM');
    const beforeExit = failOnSignal('beforeExit');
    const uncaught = (err: unknown) => {
      void failOnSignal('uncaughtException')();
    };
    const unhandled = (err: unknown) => {
      void failOnSignal('unhandledRejection')();
    };

    process.on('SIGINT', sigint);
    process.on('SIGTERM', sigterm);
    process.on('beforeExit', beforeExit);
    process.on('uncaughtException', uncaught);
    process.on('unhandledRejection', unhandled);

    this.exitHandlerCleanup.push(() => {
      process.removeListener('SIGINT', sigint);
      process.removeListener('SIGTERM', sigterm);
      process.removeListener('beforeExit', beforeExit);
      process.removeListener('uncaughtException', uncaught);
      process.removeListener('unhandledRejection', unhandled);
    });
  }

  private cleanupExitHandlers(): void {
    for (const fn of this.exitHandlerCleanup) {
      try { fn(); } catch { /* ignore */ }
    }
    this.exitHandlerCleanup.length = 0;
  }
}
`;
}

/**
 * Emit one Session class per @preset interface. Each method on the
 * preset routes through `BaseGovernedSession.runActivity()` with its
 * fixed (eventType, activityType) tuple - the lifecycle invariants
 * ride for free.
 *
 * The `custom` preset is special: its `activity()` operation takes
 * (activityType, stage, payload) so the user supplies them at call
 * time. Stage `pre` → ActivityStarted, `post` → ActivityCompleted.
 */
function emitPresetSession(p: PresetEntry, verdictModelName: string): string {
  const sessionName = `${p.pascal}Session`;
  if (p.isCustom) {
    return `/** Free-form session - caller supplies activity_type + stage at call time. */
export class ${sessionName} extends BaseGovernedSession {
  /**
   * Run an arbitrary activity. The runtime stamps:
   *   stage="pre"  → event_type=ActivityStarted
   *   stage="post" → event_type=ActivityCompleted
   */
  async activity(
    activityType: string,
    stage: ActivityStage,
    payload: GovernedPayload,
  ): Promise<${verdictModelName}> {
    const eventType = stage === 'pre' ? 'ActivityStarted' : 'ActivityCompleted';
    return this.runActivity(eventType, activityType, payload);
  }
}`;
  }

  const methods = p.methods
    .map((m) => {
      const eventType = JSON.stringify(m.eventType);
      const activityType = JSON.stringify(m.activityType);
      return `  async ${m.name}(payload: GovernedPayload): Promise<${verdictModelName}> {
    return this.runActivity(${eventType}, ${activityType}, payload);
  }`;
    })
    .join('\n\n');

  return `/** Session for the \`${p.name}\` preset - methods match the framework's hook names. */
export class ${sessionName} extends BaseGovernedSession {
${methods}
}`;
}

/**
 * Emit the `presets` registry - maps every camelCase preset name to
 * its Session constructor. Users do `presets.claudeCode` and get the
 * right class.
 */
function emitPresetsRegistry(presets: PresetEntry[]): string {
  const entries = presets
    .map((p) => `  ${p.camel}: ${p.pascal}Session,`)
    .join('\n');
  return `/**
 * Registry of every framework preset. Pass one as \`config.preset\` to
 * \`govern()\` and the typed session inside the callback will match.
 *
 * \`\`\`ts
 * await govern({ core, preset: presets.claudeCode }, async (session) => {
 *   await session.preToolUse({ input: [...] });
 * });
 * \`\`\`
 */
export const presets = {
${entries}
} as const;

export type Presets = typeof presets;
export type PresetCtor = Presets[keyof Presets];`;
}

/**
 * Emit the public `govern<S>()` helper. Generic over a preset class so
 * the session inside the callback gets the matching typed methods.
 */
function emitGovernHelper(verdictModelName: string): string {
  return `/**
 * Open a workflow envelope, run \`body\` with the typed session, and
 * finalize (Workflow{Completed,Failed}) on return - even if \`body\`
 * throws. Process-exit handlers fire WorkflowFailed best-effort if the
 * runtime dies mid-session.
 *
 * For single-process consumers (mobile, extension, MCP, custom Node).
 * For cross-process / harness-owned workflows (claude-hooks, cursor-hooks)
 * use \`govern.attach()\` instead.
 *
 * \`\`\`ts
 * await govern({ core, preset: presets.claudeCode }, async (session) => {
 *   await session.preToolUse({ input: [...] });
 * });
 * \`\`\`
 */
export async function govern<S extends PresetCtor, T>(
  config: GovernedSessionConfig & { preset: S },
  body: (session: InstanceType<S>) => Promise<T>,
): Promise<T> {
  const { preset: Ctor, ...sessionConfig } = config;
  const session = new Ctor(sessionConfig) as InstanceType<S>;
  try {
    await (session as unknown as BaseGovernedSession).workflowStarted();
    const result = await body(session);
    await (session as unknown as BaseGovernedSession).workflowCompleted();
    return result;
  } catch (err) {
    await (session as unknown as BaseGovernedSession).workflowFailed(err);
    throw err;
  }
}

/**
 * Attach a session to an existing workflow. For consumers where the
 * harness (Claude Code, Cursor, an external orchestrator) owns the
 * workflow lifecycle and the consumer fires individual activity events
 * across many short-lived processes.
 *
 * Differences vs \`govern()\`:
 *   - No auto-WorkflowStarted (caller fires \`session.workflowStarted()\`
 *     explicitly when the harness signals session start).
 *   - No auto-WorkflowCompleted (caller fires it on session end).
 *   - No process-exit handlers by default (a fresh process per hook is
 *     normal flow, not workflow failure).
 *   - \`workflowId\` and \`runId\` are REQUIRED on the config - the harness
 *     persists them across processes.
 *
 * \`\`\`ts
 * const session = govern.attach({
 *   core, agentId,
 *   preset: presets.claudeCode,
 *   workflowId, runId,         // read from your harness's session store
 * });
 *
 * if (firstHookInSession) await session.workflowStarted();
 * const verdict = await session.preToolUse({ input: [...] });
 * if (lastHookInSession) await session.workflowCompleted();
 * \`\`\`
 */
function governAttach<S extends PresetCtor>(
  config: Omit<GovernedSessionConfig, 'workflowId' | 'runId' | 'registerExitHandlers'> & {
    preset: S;
    workflowId: string;
    runId: string;
    /** Default \`false\` - fresh-process-per-hook is normal flow, not failure. */
    registerExitHandlers?: boolean;
  },
): InstanceType<S> {
  const { preset: Ctor, ...rest } = config;
  return new Ctor({
    ...rest,
    registerExitHandlers: rest.registerExitHandlers ?? false,
    attached: true,
  }) as InstanceType<S>;
}

// Namespace merge so consumers see \`govern.attach(...)\` typed.
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace govern {
  export const attach = governAttach;
}
`;
}

/** Verdict-mapping helpers shared across all preset session classes. */
function emitVerdictHelpers(verdictModelName: string): string {
  return `function mapVerdict(response: GovernanceVerdictResponse): ${verdictModelName} {
  return {
    arm: normalizeArm(response.verdict ?? response.action ?? 'allow'),
    approvalId: response.approval_id,
    approvalExpiresAt: response.approval_expiration_time,
    reason: response.reason,
    riskScore: response.risk_score ?? 0,
    trustTier: response.trust_tier ?? undefined,
    guardrailsResult: mapGuardrailsResult(response.guardrails_result),
  };
}

function mapGuardrailsResult(
  raw: GovernanceVerdictResponse['guardrails_result'],
): GuardrailsVerdict | undefined {
  if (!raw) return undefined;
  return {
    inputType: (raw.input_type as 'activity_input' | 'activity_output') ?? 'activity_input',
    redactedInput: raw.redacted_input,
    validationPassed: raw.validation_passed !== false,
    reasons: ((raw.reasons ?? []) as Array<{ type?: string; field?: string; reason?: string }>).map((r) => ({
      type: String(r.type ?? ''),
      field: r.field,
      reason: String(r.reason ?? ''),
    })),
    fieldResults: ((raw.results ?? []) as Array<{ results?: Array<{ field?: string; status?: string; reason?: string }> }>)
      .flatMap((g) => (g.results ?? []).map((fr) => ({
        field: String(fr.field ?? ''),
        status: (fr.status as 'allowed' | 'blocked' | 'redacted' | 'skipped') ?? 'skipped',
        reason: fr.reason,
      }))),
  };
}

function normalizeArm(value: string): VerdictArm {
  switch (value) {
    case 'allow':
    case 'continue':
      return 'allow';
    case 'constrain':
      return 'constrain';
    case 'require_approval':
    case 'require-approval':
      return 'require_approval';
    case 'block':
      return 'block';
    case 'halt':
    case 'stop':
      return 'halt';
    default:
      return 'allow';
  }
}

function errorInfoFrom(value: unknown): { type: string; message: string } | undefined {
  if (value == null) return undefined;
  if (value instanceof Error) {
    return { type: value.name || 'Error', message: value.message };
  }
  return { type: typeof value, message: String(value) };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Multiply a base interval by a uniform random factor in [1-fraction, 1+fraction].
 * Used by the approval poll loop to spread requests across a fleet.
 * Negative or > 1 jitter clamps to [0, 1] so callers can't create
 * negative or > 200% intervals by accident.
 */
function applyJitter(baseMs: number, fraction: number): number {
  const f = Math.max(0, Math.min(1, fraction));
  if (f === 0) return baseMs;
  const noise = (Math.random() * 2 - 1) * f; // [-f, f]
  return baseMs * (1 + noise);
}
`;
}

function emitNamespaceTypes(
  program: Program,
  project: Project,
  repoRoot: string,
  namespaceName: string,
  outRel: string,
): void {
  const ns = findNamespace(program, namespaceName);
  if (!ns) return;
  if (ns.enums.size === 0 && ns.models.size === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  for (const [enumName, enumType] of ns.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of ns.models) {
    // Skip the built-in Array/Record templates that show up under `models`
    // when other models reference them.
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }
}

function emitInterface(name: string, model: Model): string {
  const lines: string[] = [`export interface ${name} {`];
  for (const [propName, prop] of model.properties) {
    const optional = prop.optional ? '?' : '';
    lines.push(`  ${quoteIdent(propName)}${optional}: ${tspTypeToTs(prop.type)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function emitInterfaceFromOps(name: string, iface: Interface): string {
  const lines: string[] = [`export interface ${name} {`];
  for (const [opName, op] of iface.operations) {
    lines.push(`  ${quoteIdent(opName)}${operationSignature(op)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function operationSignature(op: Operation): string {
  const params: string[] = [];
  for (const [pname, p] of op.parameters.properties) {
    const optional = p.optional ? '?' : '';
    params.push(`${quoteIdent(pname)}${optional}: ${tspTypeToTs(p.type)}`);
  }
  const ret = tspTypeToTs(op.returnType);
  return `(${params.join(', ')}): ${ret}`;
}

// Coarse Type → TS lowering. Sufficient for the env+cli surfaces; the
// govern protocol uses richer types (`unknown[]`, `utcDateTime`,
// `float64`) and will need this expanded when its emitter lands.
function tspTypeToTs(type: Type): string {
  switch (type.kind) {
    case 'Scalar': {
      const n = type.name;
      if (n === 'string' || n === 'url') return 'string';
      if (n === 'boolean') return 'boolean';
      if (n === 'numeric' || n === 'int8' || n === 'int16' || n === 'int32' || n === 'int64')
        return 'number';
      if (n === 'float' || n === 'float32' || n === 'float64' || n === 'decimal') return 'number';
      if (n === 'utcDateTime' || n === 'offsetDateTime' || n === 'plainDate') return 'string';
      if (n === 'unknown') return 'unknown';
      return 'string';
    }
    case 'Enum': {
      // Named enums round-trip as their TS type alias; only inline the
      // member union when the enum is anonymous.
      if (type.name) return type.name;
      const members = [...type.members.values()].map((m) =>
        JSON.stringify(m.value ?? m.name),
      );
      return members.join(' | ');
    }
    case 'Model': {
      // Built-in template instantiations: Array<T> -> T[], Record<T> -> Record<string, T>
      if (type.name === 'Array' && type.templateMapper?.args.length) {
        const arg = type.templateMapper.args[0] as Type;
        return `${tspTypeToTs(arg)}[]`;
      }
      if (type.name === 'Record' && type.templateMapper?.args.length) {
        const arg = type.templateMapper.args[0] as Type;
        return `Record<string, ${tspTypeToTs(arg)}>`;
      }
      if (type.name) return type.name;
      // Anonymous inline model.
      const props: string[] = [];
      for (const [pn, p] of type.properties) {
        const o = p.optional ? '?' : '';
        props.push(`${quoteIdent(pn)}${o}: ${tspTypeToTs(p.type)}`);
      }
      return `{ ${props.join('; ')} }`;
    }
    case 'Intrinsic':
      if (type.name === 'void') return 'void';
      if (type.name === 'null') return 'null';
      return 'unknown';
    case 'String':
      return JSON.stringify((type as { value: string }).value);
    case 'Number':
      return String((type as { value: number }).value);
    case 'Boolean':
      return String((type as { value: boolean }).value);
    case 'Union': {
      const variants = [...type.variants.values()].map((v) => tspTypeToTs(v.type));
      return variants.join(' | ');
    }
    case 'Tuple':
      return `[${(type as { values: Type[] }).values.map(tspTypeToTs).join(', ')}]`;
    default:
      return 'unknown';
  }
}

interface EnvVarBindingRow {
  field: string;
  envVar: { name: string; defaultValue: string | undefined };
}

function collectEnvVarBindings(program: Program, model: Model): EnvVarBindingRow[] {
  const out: EnvVarBindingRow[] = [];
  for (const [name, prop] of model.properties) {
    const ev = getEnvVar(program, prop);
    if (ev) out.push({ field: name, envVar: { name: ev.name, defaultValue: ev.defaultValue } });
  }
  return out;
}

function findNamespace(program: Program, name: string): Namespace | undefined {
  // Supports both simple ("OpenboxBackend") and dotted paths
  // ("OpenboxGovern.Adapters") for nested namespace lookup.
  if (name.includes('.')) {
    const parts = name.split('.');
    let cur: Namespace | undefined = program.getGlobalNamespaceType();
    for (const part of parts) {
      if (!cur) return undefined;
      cur = cur.namespaces.get(part);
    }
    return cur;
  }
  const stack = [program.getGlobalNamespaceType()];
  while (stack.length) {
    const ns = stack.pop()!;
    if (ns.name === name) return ns;
    for (const sub of ns.namespaces.values()) stack.push(sub);
  }
  return undefined;
}

function quoteIdent(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function tsRegexLiteral(pattern: string): string {
  // RuntimeConfig stores patterns as JS regex source. Wrap in `/.../`
  // so the emitted file uses native RegExp literal form.
  return `/${pattern.replace(/\//g, '\\/')}/`;
}

/**
 * Compile an OpenAPI-style path template (`/agent/{id}/guardrails`) to
 * a regex literal that matches a realized path (`/agent/abc-123/guardrails`).
 * Each `{param}` becomes `[^/]+`. Other regex-special chars in the template
 * (rare - only `.` shows up in routes like `/governance.evaluate`) get
 * escaped. Anchored with `^…$` so a literal-prefix path can't false-match.
 */
function pathTemplateToRegex(template: string): string {
  // Escape regex-special chars EXCEPT the curly-brace placeholder syntax,
  // which we replace separately.
  const REGEX_SPECIALS = /[.*+?^${}()|[\]\\]/g;
  // First, separate placeholders from literal segments.
  const parts = template.split(/(\{[^}]+\})/);
  const compiled = parts
    .map((p) => {
      if (/^\{[^}]+\}$/.test(p)) return '[^/]+';
      return p.replace(REGEX_SPECIALS, '\\$&');
    })
    .join('');
  return `/^${compiled.replace(/\//g, '\\/')}$/`;
}
