// TypeSpec → TypeScript emitter for the OpenBox SDK monorepo.
//
// Each emit*() function targets one workspace package under ts/. The
// outputs land in `<package>/src/generated/` and are wired into the
// hand-written index via re-export. We never overwrite hand-written
// code; all generated files start with a `// AUTO-GENERATED` banner
// and live in their own subdir so a `git status` makes drift obvious.
//
// The emitter is pulled in via `tspconfig.yaml`'s emitter list
// alongside @typespec/openapi3 - same compile pass, separate output
// dirs.

import { readFileSync } from 'fs';
import { Project, IndentationText, NewLineKind, QuoteKind } from 'ts-morph';
import type {
  EmitContext,
  Interface,
  Model,
  Namespace,
  Operation,
  Program,
  Type,
} from '@typespec/compiler';
import { resolvePath } from '@typespec/compiler';
import { listHttpOperationsIn } from '@typespec/http';
import { getEnvVar, getTokenFormat, isOsPath } from '@openbox/typespec-env/decorators';
import { getCommand, getFlag } from '@openbox/typespec-cli/decorators';
import { getActivity, getWorkflow, isVerdict } from '@openbox/typespec-workflow/decorators';

const BANNER = `// AUTO-GENERATED by codegen/emitters/ts. DO NOT EDIT.
// Regenerate with: npm run specs:compile
`;

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const repoRoot = resolveRepoRoot(context);
  const project = newTsMorphProject();

  emitEnvPackage(program, project, repoRoot);
  emitCliPackage(program, project, repoRoot);
  emitEndpointManifest(program, project, repoRoot, 'OpenboxBackend', 'BACKEND_ENDPOINT_MANIFEST', 'ts/client/src/generated/endpoint-manifest.ts');
  emitEndpointManifest(program, project, repoRoot, 'OpenboxCore', 'CORE_ENDPOINT_MANIFEST', 'ts/core-client/src/generated/endpoint-manifest.ts');
  emitNamespaceTypes(program, project, repoRoot, 'OpenboxCore', 'ts/core-client/src/generated/core-types.ts');
  emitGovernProtocol(program, project, repoRoot);
  emitWrapperMethods(program, project, repoRoot, {
    namespaceName: 'OpenboxBackend',
    outRel: 'ts/client/src/generated/wrapper-methods.ts',
    pathsImport: '@openbox/types',
    pathsAlias: 'Backend',
    className: 'OpenBoxClientWrapperBase',
  });
  emitWrapperMethods(program, project, repoRoot, {
    namespaceName: 'OpenboxCore',
    outRel: 'ts/core-client/src/generated/wrapper-methods.ts',
    pathsImport: '@openbox/types',
    pathsAlias: 'Core',
    className: 'OpenBoxCoreClientWrapperBase',
  });

  await project.save();
}

// ---------------------------------------------------------------------------
// HTTP wrapper-method body emit
// ---------------------------------------------------------------------------
//
// For each endpoint declared on the namespace, generate a method body of
// the form `this.<verb>(<path>, <body>?, <opts>?)`. The hand-written
// wrapper class (OpenBoxClient / OpenBoxCoreClient) extends the
// generated `<Service>WrapperBase` to inherit all the wire methods.
// Adds 130+ methods to OpenBoxClient and 4 to OpenBoxCoreClient
// without a code edit.

interface WrapperMethodSpec {
  name: string;
  verb: string; // get / post / put / patch / delete
  pathTemplate: string; // backtick-template form with ${arg} placeholders
  pathParams: { name: string; tsType: string }[];
  bodyParam: { name: string; tsType: string } | null;
  queryParam: { name: string; tsType: string } | null;
  responseTsType: string;
}

interface WrapperEmitOptions {
  namespaceName: string;
  outRel: string;
  pathsImport: string; // e.g. '@openbox/types'
  pathsAlias: string; // 'Backend' | 'Core' - namespace re-export alias
  className: string;
}

function emitWrapperMethods(
  program: Program,
  project: Project,
  repoRoot: string,
  opts: WrapperEmitOptions,
): void {
  const ns = findNamespace(program, opts.namespaceName);
  if (!ns) return;

  const [ops] = listHttpOperationsIn(program, ns);
  if (ops.length === 0) return;

  const methods: WrapperMethodSpec[] = [];
  const seen = new Set<string>();
  for (const op of ops) {
    const spec = wrapperMethodFor(op);
    if (!spec) continue;
    // Dedup by method name in case operationIds collide after stripping
    // the controller prefix.
    if (seen.has(spec.name)) continue;
    seen.add(spec.name);
    methods.push(spec);
  }

  if (methods.length === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, opts.outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  out.addStatements(emitWrapperBaseClass(opts, methods));
}

type HttpOp = ReturnType<typeof listHttpOperationsIn>[0][number];

// Curated operationId → methodName map. Avoids collisions when multiple
// controllers share a verb (e.g. AgentController_list, ApiKeyController_list,
// WebhookController_list, MemberController_list all map to a unique
// `listAgents` / `listApiKeys` / `listWebhooks` / `getMembers`). Lives in
// codegen/method-names.json as a hand-curated artifact so consumers across
// languages can converge on the same names.
let CURATED_METHOD_NAMES: Record<string, string> = {};
try {
  const raw = readFileSync(resolvePath(process.cwd(), 'codegen/method-names.json'), 'utf8');
  CURATED_METHOD_NAMES = JSON.parse(raw);
} catch {
  // First-run before the file exists; emitter falls back to the bare
  // operationId-stripping heuristic below.
}

function wrapperMethodFor(op: HttpOp): WrapperMethodSpec | null {
  const opId = op.operation.name;
  let methodName: string;
  if (CURATED_METHOD_NAMES[opId]) {
    methodName = CURATED_METHOD_NAMES[opId];
  } else {
    // Fallback heuristic: strip the `<Tag>Controller_` prefix. Used only
    // for new ops that haven't been added to method-names.json yet - they
    // get the bare verb (e.g. `list`) and may collide; the next manual
    // run of `node /tmp/build-name-map.mjs` (or hand-edit) curates a name.
    methodName = opId;
    const m = opId.match(/^([A-Z][a-zA-Z]*Controller)_(.+)$/);
    if (m) methodName = m[2];
  }

  const pathParams: { name: string; tsType: string }[] = [];
  let bodyParam: { name: string; tsType: string } | null = null;
  let queryParam: { name: string; tsType: string } | null = null;

  for (const p of op.parameters.parameters) {
    if (p.type === 'path') {
      pathParams.push({ name: p.name, tsType: tspTypeToTs(p.param.type) });
    } else if (p.type === 'query') {
      // Multiple query params get flattened by callers via a single options
      // bag; surface as `Record<string, unknown>` for now (the openapi-typescript
      // -typed helpers in the hand-written wrapper coerce it back to the right shape).
      queryParam = { name: 'query', tsType: 'Record<string, unknown>' };
    }
  }

  if (op.parameters.body && 'type' in op.parameters.body && op.parameters.body.type) {
    bodyParam = { name: 'body', tsType: tspTypeToTs(op.parameters.body.type) };
  }

  // Response - pick the first 2xx body if any.
  let responseTsType = 'unknown';
  for (const r of op.responses) {
    const status =
      typeof r.statusCodes === 'number'
        ? r.statusCodes
        : typeof r.statusCodes === 'object' && r.statusCodes !== null
          ? r.statusCodes.start
          : 0;
    if (status >= 200 && status < 300) {
      for (const content of r.responses) {
        if (content.body && 'type' in content.body && content.body.type) {
          responseTsType = tspTypeToTs(content.body.type);
          break;
        }
      }
      break;
    }
  }

  // Build a backtick-template path: `/agent/${agentId}/guardrails`
  let pathTemplate = op.path;
  for (const p of pathParams) {
    pathTemplate = pathTemplate.replace(`{${p.name}}`, `\${${p.name}}`);
  }

  return {
    name: methodName,
    verb: op.verb.toLowerCase(),
    pathTemplate,
    pathParams,
    bodyParam,
    queryParam,
    responseTsType,
  };
}

function emitWrapperBaseClass(opts: WrapperEmitOptions, methods: WrapperMethodSpec[]): string[] {
  // Helper-fn name per verb. `delete` is reserved → `del` in our wrappers.
  // Helpers are namespaced with `http` prefix to avoid clashing with
  // method names that also start with `get` / `post` / etc. (e.g.
  // `getProfile`, `postEvent`). TypeScript would otherwise read those
  // as overloads of the abstract base method.
  const verbToHelper: Record<string, string> = {
    get: 'httpGet',
    post: 'httpPost',
    put: 'httpPut',
    patch: 'httpPatch',
    delete: 'httpDelete',
  };

  const lines: string[] = [];

  // Import the openapi-typescript output once at the top so every
  // method's response type can be expressed via indexed access:
  //
  //   Backend.paths['/auth/profile']['get']['responses']['200']['content']['application/json']
  //
  // This sidesteps the "PaginatedResponse<T> inlining" problem - we
  // never need a named alias for the generic instantiation; the
  // openapi-typescript path object already has the structural type.
  lines.push(`import type { ${opts.pathsAlias} } from '${opts.pathsImport}';`);
  lines.push('');

  // Path -> verb -> argument shape derived from `paths`. Each
  // method below references these via indexed access so changes to
  // the spec flow through openapi-typescript regen automatically.
  lines.push(`type Paths = ${opts.pathsAlias}.paths;`);
  lines.push(`type RequestBodyOf<P extends keyof Paths, V extends keyof Paths[P]> =`);
  lines.push(
    `  Paths[P][V] extends { requestBody?: { content: { 'application/json': infer B } } } ? B : never;`,
  );
  lines.push(`type ResponseOf<P extends keyof Paths, V extends keyof Paths[P]> =`);
  lines.push(
    `  Paths[P][V] extends { responses: infer R } ? R extends Record<200 | 201, { content: { 'application/json': infer J } }> ? J : R extends Record<200 | 201, infer N> ? (N extends { description?: string } ? unknown : never) : unknown : unknown;`,
  );
  lines.push('');

  lines.push(`/**`);
  lines.push(
    ` * AUTO-GENERATED wrapper base class - every HTTP operation declared on`,
  );
  lines.push(` * the ${opts.namespaceName} TypeSpec namespace becomes a typed method here.`);
  lines.push(` * Hand-written wrappers (OpenBoxClient / OpenBoxCoreClient) extend this`);
  lines.push(` * class and own construction + the protected helper methods that the`);
  lines.push(` * generated bodies call into. Adding/removing/renaming an endpoint in`);
  lines.push(` * the spec flows through here without a code edit on the impl side.`);
  lines.push(` */`);
  lines.push(`export abstract class ${opts.className} {`);
  // Helpers exposed by the hand-written wrapper. The `http` prefix
  // avoids name clashes with API methods like `getProfile` / `postEvent`.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lines.push(`  protected abstract httpGet<T>(path: string, query?: any): Promise<T>;`);
  lines.push(`  protected abstract httpPost<T>(path: string, body?: unknown): Promise<T>;`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lines.push(`  protected abstract httpPut<T>(path: string, body?: unknown, query?: any): Promise<T>;`);
  lines.push(`  protected abstract httpPatch<T>(path: string, body?: unknown): Promise<T>;`);
  lines.push(`  protected abstract httpDelete<T>(path: string, body?: unknown): Promise<T>;`);
  lines.push('');
  for (const method of methods) {
    const helper = verbToHelper[method.verb];
    if (!helper) continue;

    // Build the literal-string `paths[<path>][<verb>]` lookup keys.
    // openapi-typescript emits paths like `'/agent/list'` and verbs as
    // `'get' | 'post' | ...` keys. We use the *path with placeholders*
    // (e.g. `/agent/{agentId}`) - that's what openapi-typescript keys
    // by, not the runtime substituted form.
    const pathLiteral = JSON.stringify(method.pathTemplate.replace(/\$\{[^}]+\}/g, (_, n) => '{' + n + '}'));
    // Recover the original `{x}` form from the `${x}` template.
    // Actually pathTemplate started as `${x}` so we need to convert back.
    const specPathLiteral = JSON.stringify(
      method.pathTemplate.replace(/\$\{([^}]+)\}/g, '{$1}'),
    );
    const verbLiteral = JSON.stringify(method.verb);

    const reqType = method.bodyParam
      ? `RequestBodyOf<${specPathLiteral}, ${verbLiteral}>`
      : null;
    const respType = `ResponseOf<${specPathLiteral}, ${verbLiteral}>`;

    const args: string[] = [];
    for (const p of method.pathParams) args.push(`${p.name}: string`);
    if (reqType) args.push(`body: ${reqType}`);
    if (method.queryParam) args.push(`query?: Record<string, unknown>`);

    const callArgs = [`\`${method.pathTemplate}\``];
    if (method.verb === 'get') {
      if (method.queryParam) callArgs.push('query');
    } else if (method.verb === 'put') {
      if (reqType) callArgs.push('body');
      else callArgs.push('undefined');
      if (method.queryParam) callArgs.push('query');
    } else {
      if (reqType) callArgs.push('body');
    }

    lines.push(`  async ${method.name}(${args.join(', ')}): Promise<${respType}> {`);
    lines.push(`    return this.${helper}<${respType}>(${callArgs.join(', ')});`);
    lines.push(`  }`);
    lines.push('');
    // suppress unused var warnings
    void pathLiteral;
  }
  lines.push(`}`);
  return lines;
}

function newTsMorphProject(): Project {
  return new Project({
    useInMemoryFileSystem: false,
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      newLineKind: NewLineKind.LineFeed,
      quoteKind: QuoteKind.Single,
    },
  });
}

function resolveRepoRoot(context: EmitContext): string {
  // emitter-output-dir is configured per-emitter in tspconfig.yaml; we
  // ignore it and write directly into ts/<package>/src/generated/. The
  // tspconfig still has to set *something*, so we treat that path as
  // an anchor and walk back to the repo root.
  return resolvePath(context.emitterOutputDir, '..', '..', '..');
}

// ---------------------------------------------------------------------------
// Env package emit
// ---------------------------------------------------------------------------

function emitEnvPackage(program: Program, project: Project, repoRoot: string): void {
  const envNamespace = findNamespace(program, 'OpenboxEnv');
  if (!envNamespace) return;

  const envName = envNamespace.enums.get('EnvName');
  const envConfig = envNamespace.models.get('EnvConfig');
  const runtimeConfig = envNamespace.models.get('RuntimeConfig');
  const credentials = envNamespace.models.get('Credentials');
  const tokenEntry = envNamespace.models.get('TokenEntry');
  const tokenStoreModel = envNamespace.models.get('TokenStore');
  const envLoader = envNamespace.interfaces.get('EnvLoader');
  const tokenCodec = envNamespace.interfaces.get('TokenCodec');
  const clientNameResolver = envNamespace.interfaces.get('ClientNameResolver');
  const osPathResolver = envNamespace.interfaces.get('OsPathResolver');
  const clientVariantMarker = envNamespace.models.get('ClientVariant');
  const clientVariantPattern = clientVariantMarker?.properties.get('value')
    ? getTokenFormat(program, clientVariantMarker.properties.get('value')!)
    : undefined;

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts', 'env', 'src', 'generated', 'env-bindings.ts'),
    '',
    { overwrite: true },
  );

  // ts-morph's import-attribute API double-quotes the attribute value, so
  // skip it and write the import line as plain text.
  out.insertText(
    0,
    BANNER +
      '\n' +
      `import environmentsJson from '../../../../specs/environments.json' with { type: 'json' };\n\n`,
  );

  // EnvName + EnvConfig - generated from spec, imported (not redeclared)
  // by hand-written code in the same package.
  if (envName) {
    const members = [...envName.members.values()].map((m) => JSON.stringify(m.value ?? m.name));
    out.addStatements([`export type EnvName = ${members.join(' | ')};`, '']);
  }
  if (envConfig) {
    out.addStatements([emitInterface('EnvConfig', envConfig), '']);
  }
  out.addStatements([
    `export const ENVIRONMENTS: Record<EnvName, EnvConfig> = environmentsJson as Record<
  EnvName,
  EnvConfig
>;`,
    '',
  ]);

  // Generate the env-var binding table from @env_var decorators on
  // RuntimeConfig. Used by `resolveUrls()` so adding a new field on
  // the .tsp side automatically flows through.
  if (runtimeConfig) {
    const bindings = collectEnvVarBindings(program, runtimeConfig);
    if (bindings.length > 0) {
      out.addStatements([
        `export const ENV_VAR_BINDINGS = {`,
        ...bindings.map(
          (b) => `  ${quoteIdent(b.field)}: ${JSON.stringify(b.envVar)} as const,`,
        ),
        `} as const;`,
        '',
      ]);
    }
  }

  // Generate the API-key validator from @token_format on Credentials.
  if (credentials) {
    const apiKey = credentials.properties.get('apiKey');
    const pattern = apiKey ? getTokenFormat(program, apiKey) : undefined;
    if (pattern) {
      out.addStatements([
        `const API_KEY_PATTERN = ${tsRegexLiteral(pattern)};`,
        '',
        `export function validateApiKeyFormat(value: string): true | string {
  if (!API_KEY_PATTERN.test(value)) {
    return 'OPENBOX_API_KEY must match obx_(live|test)_<48hex>';
  }
  return true;
}`,
        '',
      ]);
    }
  }

  // Generate an OS-path resolver hint table for fields tagged @os_path.
  if (credentials) {
    const osPathFields: string[] = [];
    for (const [name, prop] of credentials.properties) {
      if (isOsPath(program, prop)) osPathFields.push(name);
    }
    if (osPathFields.length > 0) {
      out.addStatements([
        `export const OS_PATH_FIELDS = ${JSON.stringify(osPathFields)} as const;`,
        '',
      ]);
    }
  }

  // Persisted-tokens shape (TokenEntry + TokenStore) - codec wire
  // format every language must agree on.
  if (tokenEntry) {
    out.addStatements([emitInterface('TokenEntry', tokenEntry), '']);
  }
  if (tokenStoreModel) {
    out.addStatements([emitInterface('TokenStore', tokenStoreModel), '']);
  }

  // FeatureMap is the "convenience alias for Record<string, boolean>"
  // that the hand-written code imports today; we keep it as a generated
  // alias instead of redeclaring on the impl side.
  out.addStatements([
    `export type FeatureMap = NonNullable<TokenEntry['features']>;`,
    '',
  ]);

  // Construction-time config models - `BackendClientConfig` /
  // `CoreClientConfig` / `RetryConfig` / `RateLimitConfig` /
  // `TokenPair` / `ApiError`. Emit anything we haven't already
  // hand-picked above so adding a new option model in the spec
  // flows through without an emitter edit.
  const alreadyEmitted = new Set([
    'EnvConfig',
    'RuntimeConfig',
    'Credentials',
    'TokenEntry',
    'TokenStore',
    'ClientVariant',
    'Runtime',
  ]);
  for (const [modelName, model] of envNamespace.models) {
    if (alreadyEmitted.has(modelName)) continue;
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }

  // EnvLoader / TokenCodec / ClientNameResolver - runtime contracts
  // that hand-written code must implement. Drift between spec and
  // impl fails `tsc --noEmit`.
  if (envLoader) {
    out.addStatements([emitInterfaceFromOps('EnvLoader', envLoader), '']);
  }
  if (tokenCodec) {
    out.addStatements([emitInterfaceFromOps('TokenCodec', tokenCodec), '']);
  }
  if (clientNameResolver) {
    out.addStatements([emitInterfaceFromOps('ClientNameResolver', clientNameResolver), '']);
  }
  if (osPathResolver) {
    out.addStatements([emitInterfaceFromOps('OsPathResolver', osPathResolver), '']);
  }

  // OsPathScope enum - drives the per-OS path lookup. Emit the
  // string-literal union form so callers can `import type { OsPathScope }`
  // and write `resolveOsPath('tokens')`.
  const osPathScopeEnum = envNamespace.enums.get('OsPathScope');
  if (osPathScopeEnum) {
    const members = [...osPathScopeEnum.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type OsPathScope = ${members.join(' | ')};`, '']);
  }
  if (clientVariantPattern) {
    out.addStatements([
      `export const CLIENT_VARIANT_PATTERN = ${tsRegexLiteral(clientVariantPattern)};`,
      '',
    ]);
  }
}

// ---------------------------------------------------------------------------
// CLI package emit
// ---------------------------------------------------------------------------

interface FlagEntry {
  name: string;
  long: string;
  short: string | undefined;
  description: string;
  env: string | undefined;
  optional: boolean;
  tsType: string;
}

interface SubcommandEntry {
  name: string;
  flags: FlagEntry[];
}

interface ManifestEntry {
  command: string;
  description: string | undefined;
  interfaceName: string;
  subcommands: SubcommandEntry[];
}

function emitCliPackage(program: Program, project: Project, repoRoot: string): void {
  const cliNamespace = findNamespace(program, 'OpenboxCli');
  if (!cliNamespace) return;

  // Skip emit if no @cli_command interfaces present.
  const commands: { name: string; iface: Interface }[] = [];
  for (const [name, iface] of cliNamespace.interfaces) {
    if (getCommand(program, iface)) commands.push({ name, iface });
  }
  if (commands.length === 0) return;

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts', 'cli', 'src', 'generated', 'cli-bindings.ts'),
    '',
    { overwrite: true },
  );

  out.insertText(0, BANNER + '\n\n');

  // Emit every enum + model referenced by the interfaces, so the emitted
  // file is self-contained - no `import type { EnvFlag } from '../../...'`
  // dance for hand-written code.
  for (const [enumName, enumType] of cliNamespace.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of cliNamespace.models) {
    out.addStatements([emitInterface(modelName, model), '']);
  }

  const manifest: ManifestEntry[] = [];

  for (const { name, iface } of commands) {
    const cmd = getCommand(program, iface)!;

    out.addStatements([emitInterfaceFromOps(name, iface), '']);

    const subcommands: SubcommandEntry[] = [];
    for (const [opName, op] of iface.operations) {
      const flags: FlagEntry[] = [];
      for (const [pname, p] of op.parameters.properties) {
        const fb = getFlag(program, p);
        if (!fb) continue;
        flags.push({
          name: pname,
          long: kebabCaseLocal(pname),
          short: fb.short,
          description: fb.description,
          env: fb.env,
          optional: p.optional,
          tsType: tspTypeToTs(p.type),
        });
      }
      subcommands.push({ name: opName, flags });
    }

    manifest.push({
      command: cmd.name,
      description: cmd.description,
      interfaceName: name,
      subcommands,
    });
  }

  out.addStatements([
    '/**',
    ' * Canonical CLI surface - every command-tree node declared in',
    ' * specs/typespec/cli/. The hand-written commander registration in',
    ' * ts/cli/src/main.ts walks this manifest so a spec edit (rename a',
    ' * flag, add a subcommand) propagates without a code edit.',
    ' */',
    `export const CLI_COMMAND_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;`,
    '',
    'export type CliCommandManifest = typeof CLI_COMMAND_MANIFEST;',
    '',
  ]);
}

function kebabCaseLocal(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

// ---------------------------------------------------------------------------
// HTTP endpoint manifest emit (ts/client + ts/core-client)
// ---------------------------------------------------------------------------
//
// Walks an HTTP-service namespace via @typespec/http's listHttpOperationsIn
// and emits a `<NAME>_ENDPOINT_MANIFEST` array of every (path, verb,
// operationId) tuple. Tests in tests/unit/endpoint-coverage.test.ts read
// the manifest and assert each entry has a matching method on the
// hand-written wrapper class - adding a route to the spec without a
// matching wrapper method now fails CI.

interface EndpointEntry {
  operationId: string;
  path: string;
  verb: string;
  // The path normalized so {placeholders} become a regex-safe form for
  // grep-matching against fetch URLs in hand-written code.
  pathPattern: string;
}

function emitEndpointManifest(
  program: Program,
  project: Project,
  repoRoot: string,
  namespaceName: string,
  exportName: string,
  outRel: string,
): void {
  const ns = findNamespace(program, namespaceName);
  if (!ns) return;

  const [ops] = listHttpOperationsIn(program, ns);
  const entries: EndpointEntry[] = ops.map((o) => ({
    operationId: o.operation.name,
    path: o.path,
    verb: o.verb,
    pathPattern: o.path.replace(/\{[^}]+\}/g, '{x}'),
  }));

  if (entries.length === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  out.addStatements([
    `/**`,
    ` * Every HTTP operation declared on the ${namespaceName} TypeSpec`,
    ` * namespace. Tests in tests/unit/endpoint-coverage.test.ts walk this`,
    ` * array and assert the hand-written wrapper class has a method`,
    ` * implementing each entry - adding a path here without a wrapper`,
    ` * method fails CI.`,
    ` */`,
    `export const ${exportName} = ${JSON.stringify(entries, null, 2)} as const;`,
    '',
    `export type ${pascal(exportName)}Entry = (typeof ${exportName})[number];`,
    '',
  ]);
}

function pascal(s: string): string {
  return s
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

// ---------------------------------------------------------------------------
// Namespace-types emit - drops every enum/model/scalar declared on a
// service namespace into a single TS file. Used to give per-package
// wrappers (ts/core-client, ts/client govern) a single import path
// for their wire types instead of redeclaring each one inline.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Govern-protocol emit - the @workflow / @activity decorator metadata
// declared on `OpenboxGovern.GovernedAgent` becomes a typed
// `ACTIVITY_MANIFEST` + `Verdict` / `GovernedPayload` types and an
// `ActivityName` literal union. Hand-written wrappers in
// `openbox-typescript-sdk` (and any future TS govern() variant) read
// these to drive the WorkflowStarted -> ActivityStarted ->
// ActivityCompleted -> WorkflowCompleted sequence with canonical
// activity_type strings.
// ---------------------------------------------------------------------------

interface ActivityEntry {
  method: string;
  canonicalType: string;
  stage: string;
}

function emitGovernProtocol(program: Program, project: Project, repoRoot: string): void {
  const ns = findNamespace(program, 'OpenboxGovern');
  if (!ns) return;

  // Find the workflow interface (only one - `GovernedAgent`).
  let workflowIface: Interface | undefined;
  for (const [, iface] of ns.interfaces) {
    if (getWorkflow(program, iface)) {
      workflowIface = iface;
      break;
    }
  }

  const out = project.createSourceFile(
    resolvePath(repoRoot, 'ts/core-client/src/generated/govern.ts'),
    '',
    { overwrite: true },
  );
  out.insertText(0, BANNER + '\n\n');

  // Emit every enum + model in the namespace (Verdict, VerdictArm,
  // GovernedPayload). The emitter's existing `tspTypeToTs` handles
  // enum unions and named-type references.
  for (const [enumName, enumType] of ns.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of ns.models) {
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }

  if (!workflowIface) return;

  const activities: ActivityEntry[] = [];
  for (const [opName, op] of workflowIface.operations) {
    const a = getActivity(program, op);
    if (!a) continue;
    activities.push({
      method: opName,
      canonicalType: a.canonicalType,
      stage: a.stage,
    });
  }

  if (activities.length === 0) return;

  out.addStatements([
    '/**',
    ' * The set of governed activities declared in',
    ' * `specs/typespec/govern/main.tsp`. The hand-written `govern()`',
    ' * wrapper consumes this manifest to derive (a) the canonical',
    ' * `activity_type` to put on the wire and (b) the gate stage',
    " * (`pre` / `post` / `both`) per activity. Adding a new method to",
    ' * the spec\'s `GovernedAgent` interface flows through here',
    ' * without a code edit.',
    ' */',
    `export const ACTIVITY_MANIFEST = ${JSON.stringify(activities, null, 2)} as const;`,
    '',
    'export type ActivityName = (typeof ACTIVITY_MANIFEST)[number]["canonicalType"];',
    '',
    'export type ActivityManifestEntry = (typeof ACTIVITY_MANIFEST)[number];',
    '',
  ]);

  // Sanity export of the verdict-marker name so consumers can branch
  // off the type alias rather than re-deriving it.
  let verdictModelName = '';
  for (const [modelName, model] of ns.models) {
    if (isVerdict(program, model)) {
      verdictModelName = modelName;
      out.addStatements([`export type CanonicalVerdict = ${modelName};`, '']);
      break;
    }
  }

  // Emit the full workflow runtime - `GovernedSession` class +
  // `govern()` helper. Spec-driven all the way down: every method on
  // the `GovernedAgent` interface gets a generated thunk that calls
  // the private `runActivity()` orchestrator with the right canonical
  // activity_type / stage tuple. Hand-written code in this package
  // owns nothing about how the protocol fires; the runtime body
  // round-trips through the spec.
  if (verdictModelName) {
    out.addStatements([emitGovernRuntime(activities, verdictModelName), '']);
  }
}

function emitGovernRuntime(activities: ActivityEntry[], verdictModelName: string): string {
  const activityMethods = activities
    .map(
      (a) =>
        `  async ${a.method}(payload: GovernedPayload): Promise<${verdictModelName}> {
    return this.runActivity(${JSON.stringify(a.method)}, payload);
  }`,
    )
    .join('\n\n');

  const interfaceMethods = activities
    .map((a) => `  ${a.method}(payload: GovernedPayload): Promise<${verdictModelName}>;`)
    .join('\n');

  return `import { randomUUID } from 'crypto';
import type { OpenBoxCoreClient } from '../core-client.js';
import type {
  GovernanceEventPayload,
  GovernanceVerdictResponse,
} from './core-types.js';

/**
 * Construction options for \`GovernedSession\`. The \`core\` client is
 * the authenticated transport; the other fields define this workflow
 * run's identity.
 */
export interface GovernedSessionConfig {
  core: OpenBoxCoreClient;
  /** Stable identifier for this workflow run. */
  workflowId?: string;
  /** Per-attempt run identifier. */
  runId?: string;
  /** Workflow-class identifier surfaced to observability. */
  workflowType?: string;
  /** Originating runtime tag (\`langgraph\` / \`temporal\` / \`mastra\` / ...). */
  taskQueue?: string;
  /** Polling interval (ms) when the verdict is \`require_approval\`. */
  approvalPollIntervalMs?: number;
  /** Maximum total wait (ms) for an approval decision. */
  approvalMaxWaitMs?: number;
}

/**
 * \`GovernedAgent\` from the spec, lifted to TS types. Every method on
 * \`GovernedSession\` below implements one of these.
 */
export interface GovernedAgent {
${interfaceMethods}
}

type ActivityIndex = {
  [E in ActivityManifestEntry as E['method']]: E;
};

const ACTIVITY_BY_METHOD: ActivityIndex = Object.fromEntries(
  ACTIVITY_MANIFEST.map((entry) => [entry.method, entry] as const),
) as ActivityIndex;

function activityFor(method: keyof ActivityIndex): ActivityManifestEntry {
  const entry = ACTIVITY_BY_METHOD[method];
  if (!entry) {
    throw new Error(
      \`[govern] no manifest entry for method "\${String(method)}". Re-run \\\`npm run specs:compile\\\`.\`,
    );
  }
  return entry;
}

export class GovernedSession implements GovernedAgent {
  readonly workflowId: string;
  readonly runId: string;
  readonly workflowType: string;
  readonly taskQueue: string;

  private readonly core: OpenBoxCoreClient;
  private readonly approvalPollIntervalMs: number;
  private readonly approvalMaxWaitMs: number;
  private opened = false;
  private finalized = false;

  constructor(config: GovernedSessionConfig) {
    this.core = config.core;
    this.workflowId = config.workflowId ?? randomUUID();
    this.runId = config.runId ?? randomUUID();
    this.workflowType = config.workflowType ?? 'governed_agent';
    this.taskQueue = config.taskQueue ?? 'generic';
    this.approvalPollIntervalMs = config.approvalPollIntervalMs ?? 1_000;
    this.approvalMaxWaitMs = config.approvalMaxWaitMs ?? 60_000;
  }

  async begin(): Promise<void> {
    if (this.opened) return;
    this.opened = true;
    await this.emit({ event_type: 'WorkflowStarted' });
  }

  async complete(): Promise<void> {
    if (this.finalized) return;
    this.finalized = true;
    await this.emit({ event_type: 'WorkflowCompleted', status: 'completed' });
  }

  async fail(error?: unknown): Promise<void> {
    if (this.finalized) return;
    this.finalized = true;
    await this.emit({
      event_type: 'WorkflowFailed',
      status: 'failed',
      error: errorInfoFrom(error),
    });
  }

${activityMethods}

  private async runActivity(
    method: keyof ActivityIndex,
    payload: GovernedPayload,
  ): Promise<${verdictModelName}> {
    if (!this.opened) await this.begin();
    const entry = activityFor(method);
    const activityId = randomUUID();

    const startedVerdict = await this.emit({
      event_type: 'ActivityStarted',
      activity_id: activityId,
      activity_type: entry.canonicalType,
      activity_input: payload.input,
    });

    if (
      (entry.stage === 'pre' || entry.stage === 'both') &&
      startedVerdict.arm !== 'allow'
    ) {
      // Pre-stage block - never emit ActivityCompleted.
      return startedVerdict;
    }

    const completedVerdict = await this.emit({
      event_type: 'ActivityCompleted',
      activity_id: activityId,
      activity_type: entry.canonicalType,
      activity_input: payload.input,
      activity_output: payload.output,
    });

    if (completedVerdict.arm === 'require_approval' && completedVerdict.approvalId) {
      return this.pollApproval(activityId, completedVerdict);
    }

    return completedVerdict;
  }

  private async emit(
    event: Pick<
      GovernanceEventPayload,
      'event_type' | 'activity_id' | 'activity_type' | 'activity_input' | 'activity_output' | 'status' | 'error'
    >,
  ): Promise<${verdictModelName}> {
    const payload = {
      ...event,
      source: 'workflow-telemetry',
      workflow_id: this.workflowId,
      run_id: this.runId,
      workflow_type: this.workflowType,
      task_queue: this.taskQueue,
      timestamp: new Date().toISOString(),
    } as unknown as GovernanceEventPayload;
    const response = await this.core.evaluate(payload);
    return mapVerdict(response);
  }

  private async pollApproval(
    activityId: string,
    initial: ${verdictModelName},
  ): Promise<${verdictModelName}> {
    const deadline = Date.now() + this.approvalMaxWaitMs;
    while (Date.now() < deadline) {
      await sleep(this.approvalPollIntervalMs);
      const status = await this.core.pollApproval({
        workflow_id: this.workflowId,
        run_id: this.runId,
        activity_id: activityId,
      });
      if (!status.action || status.action === 'require_approval') continue;
      return {
        arm: normalizeArm(status.action),
        approvalId: initial.approvalId,
        approvalExpiresAt: status.approval_expiration_time,
        reason: status.reason,
        riskScore: initial.riskScore,
        trustTier: initial.trustTier,
      };
    }
    return initial;
  }
}

/**
 * Open a workflow envelope, run \`body\` with a \`GovernedAgent\`, and
 * finalize (Workflow{Completed,Failed}) on return.
 */
export async function govern<T>(
  config: GovernedSessionConfig,
  body: (session: GovernedAgent) => Promise<T>,
): Promise<T> {
  const session = new GovernedSession(config);
  try {
    await session.begin();
    const result = await body(session);
    await session.complete();
    return result;
  } catch (err) {
    await session.fail(err);
    throw err;
  }
}

function mapVerdict(response: GovernanceVerdictResponse): ${verdictModelName} {
  return {
    arm: normalizeArm(response.verdict ?? response.action ?? 'allow'),
    approvalId: response.approval_id,
    approvalExpiresAt: response.approval_expiration_time,
    reason: response.reason,
    riskScore: response.risk_score ?? 0,
    trustTier: response.trust_tier ?? undefined,
  };
}

function normalizeArm(value: string): VerdictArm {
  switch (value) {
    case 'allow':
    case 'continue':
      return 'allow';
    case 'constrain':
      return 'constrain';
    case 'require_approval':
    case 'require-approval':
      return 'require_approval';
    case 'block':
      return 'block';
    case 'halt':
    case 'stop':
      return 'halt';
    default:
      return 'allow';
  }
}

function errorInfoFrom(value: unknown): { type: string; message: string } | undefined {
  if (value == null) return undefined;
  if (value instanceof Error) {
    return { type: value.name || 'Error', message: value.message };
  }
  return { type: typeof value, message: String(value) };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
`;
}

function emitNamespaceTypes(
  program: Program,
  project: Project,
  repoRoot: string,
  namespaceName: string,
  outRel: string,
): void {
  const ns = findNamespace(program, namespaceName);
  if (!ns) return;
  if (ns.enums.size === 0 && ns.models.size === 0) return;

  const out = project.createSourceFile(resolvePath(repoRoot, outRel), '', { overwrite: true });
  out.insertText(0, BANNER + '\n\n');

  for (const [enumName, enumType] of ns.enums) {
    const members = [...enumType.members.values()].map((m) =>
      JSON.stringify(m.value ?? m.name),
    );
    out.addStatements([`export type ${enumName} = ${members.join(' | ')};`, '']);
  }
  for (const [modelName, model] of ns.models) {
    // Skip the built-in Array/Record templates that show up under `models`
    // when other models reference them.
    if (modelName === 'Array' || modelName === 'Record') continue;
    out.addStatements([emitInterface(modelName, model), '']);
  }
}

function emitInterface(name: string, model: Model): string {
  const lines: string[] = [`export interface ${name} {`];
  for (const [propName, prop] of model.properties) {
    const optional = prop.optional ? '?' : '';
    lines.push(`  ${quoteIdent(propName)}${optional}: ${tspTypeToTs(prop.type)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function emitInterfaceFromOps(name: string, iface: Interface): string {
  const lines: string[] = [`export interface ${name} {`];
  for (const [opName, op] of iface.operations) {
    lines.push(`  ${quoteIdent(opName)}${operationSignature(op)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function operationSignature(op: Operation): string {
  const params: string[] = [];
  for (const [pname, p] of op.parameters.properties) {
    const optional = p.optional ? '?' : '';
    params.push(`${quoteIdent(pname)}${optional}: ${tspTypeToTs(p.type)}`);
  }
  const ret = tspTypeToTs(op.returnType);
  return `(${params.join(', ')}): ${ret}`;
}

// Coarse Type → TS lowering. Sufficient for the env+cli surfaces; the
// govern protocol uses richer types (`unknown[]`, `utcDateTime`,
// `float64`) and will need this expanded when its emitter lands.
function tspTypeToTs(type: Type): string {
  switch (type.kind) {
    case 'Scalar': {
      const n = type.name;
      if (n === 'string' || n === 'url') return 'string';
      if (n === 'boolean') return 'boolean';
      if (n === 'numeric' || n === 'int8' || n === 'int16' || n === 'int32' || n === 'int64')
        return 'number';
      if (n === 'float' || n === 'float32' || n === 'float64' || n === 'decimal') return 'number';
      if (n === 'utcDateTime' || n === 'offsetDateTime' || n === 'plainDate') return 'string';
      if (n === 'unknown') return 'unknown';
      return 'string';
    }
    case 'Enum': {
      // Named enums round-trip as their TS type alias; only inline the
      // member union when the enum is anonymous.
      if (type.name) return type.name;
      const members = [...type.members.values()].map((m) =>
        JSON.stringify(m.value ?? m.name),
      );
      return members.join(' | ');
    }
    case 'Model': {
      // Built-in template instantiations: Array<T> -> T[], Record<T> -> Record<string, T>
      if (type.name === 'Array' && type.templateMapper?.args.length) {
        const arg = type.templateMapper.args[0] as Type;
        return `${tspTypeToTs(arg)}[]`;
      }
      if (type.name === 'Record' && type.templateMapper?.args.length) {
        const arg = type.templateMapper.args[0] as Type;
        return `Record<string, ${tspTypeToTs(arg)}>`;
      }
      if (type.name) return type.name;
      // Anonymous inline model.
      const props: string[] = [];
      for (const [pn, p] of type.properties) {
        const o = p.optional ? '?' : '';
        props.push(`${quoteIdent(pn)}${o}: ${tspTypeToTs(p.type)}`);
      }
      return `{ ${props.join('; ')} }`;
    }
    case 'Intrinsic':
      if (type.name === 'void') return 'void';
      if (type.name === 'null') return 'null';
      return 'unknown';
    case 'String':
      return JSON.stringify((type as { value: string }).value);
    case 'Number':
      return String((type as { value: number }).value);
    case 'Boolean':
      return String((type as { value: boolean }).value);
    case 'Union': {
      const variants = [...type.variants.values()].map((v) => tspTypeToTs(v.type));
      return variants.join(' | ');
    }
    case 'Tuple':
      return `[${(type as { values: Type[] }).values.map(tspTypeToTs).join(', ')}]`;
    default:
      return 'unknown';
  }
}

interface EnvVarBindingRow {
  field: string;
  envVar: { name: string; defaultValue: string | undefined };
}

function collectEnvVarBindings(program: Program, model: Model): EnvVarBindingRow[] {
  const out: EnvVarBindingRow[] = [];
  for (const [name, prop] of model.properties) {
    const ev = getEnvVar(program, prop);
    if (ev) out.push({ field: name, envVar: { name: ev.name, defaultValue: ev.defaultValue } });
  }
  return out;
}

function findNamespace(program: Program, name: string): Namespace | undefined {
  const stack = [program.getGlobalNamespaceType()];
  while (stack.length) {
    const ns = stack.pop()!;
    if (ns.name === name) return ns;
    for (const sub of ns.namespaces.values()) stack.push(sub);
  }
  return undefined;
}

function quoteIdent(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function tsRegexLiteral(pattern: string): string {
  // RuntimeConfig stores patterns as JS regex source. Wrap in `/.../`
  // so the emitted file uses native RegExp literal form.
  return `/${pattern.replace(/\//g, '\\/')}/`;
}
