// Public wrapper for the spec-generated provider capability matrix.
// Canonical data lives in specs/typespec/govern/capabilities.tsp and
// is emitted by `npm run specs:compile`.

export {
  OPENBOX_CAPABILITY_IDS,
  OPENBOX_PROVIDER_IDS,
  OPENBOX_SUPPORT_TIERS,
  PROVIDER_CAPABILITY_MATRIX,
  REFERENCE_PROVIDER_PARITY_CLOSURES,
  REFERENCE_PROVIDER_RUNTIME_AUDIT,
  PROVIDER_EVENT_CATALOG,
  PROVIDER_PLUGIN_COMPONENTS,
  PUBLIC_INTEGRATION_SUPPORT,
  GOAL_SIGNAL_GUARDS,
  USAGE_COST_CAPABILITY_GUARDS,
  USAGE_NORMALIZATION_SURFACE,
  TRACING_CAPABILITY_GUARDS,
  HITL_CAPABILITY_GUARDS,
  GUARDRAIL_CAPABILITY_GUARDS,
  POLICY_EVALUATION_GUARDS,
  RULES_INSTRUCTION_CAPABILITY_GUARDS,
  HOOK_CAPABILITY_GUARDS,
  SUBAGENTS_AGENTS_CAPABILITY_GUARDS,
  PLUGIN_CAPABILITY_GUARDS,
  SKILL_CAPABILITY_GUARDS,
  MCP_CAPABILITY_GUARDS,
  INSTALL_DOCTOR_CAPABILITY_GUARDS,
  LOCAL_STACK_SCENARIO_PATHS,
  LOCAL_STACK_SCENARIO_MATRIX,
  MCP_TOOL_SURFACES,
  MCP_PROMPT_SURFACES,
  MCP_RESOURCE_TEMPLATE_SURFACES,
  MCP_SKILL_REFERENCE_SURFACES,
  N8N_INTEGRATION_SURFACE,
} from './generated/capability-matrix.js';
export type {
  OpenBoxCapabilityId,
  OpenBoxProviderId,
  OpenBoxSupportTier,
  ReferenceProviderParityClosureEntry,
  ReferenceProviderParityClosureStatus,
  ReferenceProviderRuntimeAuditEntry,
  ReferenceProviderRuntimePromotionDecision,
  GoalSignalGuardEntry,
  UsageCostCapabilityGuardEntry,
  UsageNormalizationSurface,
  TracingCapabilityGuardEntry,
  HitlCapabilityGuardEntry,
  GuardrailCapabilityGuardEntry,
  PolicyEvaluationGuardEntry,
  RulesInstructionCapabilityGuardEntry,
  HookCapabilityGuardEntry,
  SubagentsAgentsCapabilityGuardEntry,
  PluginCapabilityGuardEntry,
  SkillCapabilityGuardEntry,
  McpCapabilityGuardEntry,
  InstallDoctorCapabilityGuardEntry,
  LocalStackScenarioMatrixContract,
  LocalStackScenarioPathSpec,
  McpPromptArgEntry,
  McpPromptSurfaceEntry,
  McpResourceTemplateSurfaceEntry,
  McpSkillReferenceSurfaceEntry,
  McpToolSurfaceEntry,
  N8nIntegrationSurface,
  ProviderCapabilityEntry,
  ProviderEventCatalogEntry,
  ProviderPluginComponentCatalogEntry,
  PublicIntegrationSupportEntry,
} from './generated/capability-matrix.js';
